### ISSUE TITLE
afther download on wndws 10 afther clicking install nothing happens

### ISSUE THREAD

**Issue by Bigrome59** [nicehash/NiceHashMiner#2020] opened 2020-04-04 18:13 UTC
**NOTE this issue tracker is for NiceHashMiner bugs/feature requests ONLY! If you need general help or have a support question related to NHM2 (OBSOLETE) or NHOS please look at https://www.nicehash.com/support first and open a ticket there if your issue is not specifically NHM related**

For general help there are several community resources available, such as https://reddit.com/r/NiceHash

There is a [documentation](https://github.com/nicehash/NiceHashMiner/tree/master/doc) available, so please check it out first. If you don't find the answer there, please create a new issue, that follows requirements stated below. 

To keep development of NiceHash Miner streamlined please make sure the following are true before posting an issue:

- Please make requests in English
- The issue has not already been reported.
- **Relevant log files are included (generally `\logs\log.txt`).**
- **The issue is with NHM and not inherent of miner executables.** This can be verified by launching the miner manually and looking for the error.
- **The issue is relevant to NHM specifically and not to the NiceHash service, NHOS or NHM2.** (see above)
- Specifications of setup such as NHM version, Windows version, and hardware are included.

Note this is a guide, you can delete this text once you ensure enough information is given

**Comment by luc1an24** [comment] 2020-04-08 09:08
Hi @Bigrome59 
Thank you for reaching out.
Does this issue still prevents you from installing NHM?
Have you tried temporary disabling firewall for the purpose of installation process?
If you have any additional information about the failed process please let me know.
Have a nice day!

**Comment by Bigrome59** [comment] 2020-04-08 20:57
Fire wall is down but still not working

**Comment by luc1an24** [comment] 2020-04-22 06:33
@Bigrome59 
Sorry didn't see your response because of email reply.
Do you have admin privileges on your computer?
Do you have any specific antivirus defender installed?
Thank you for your information.

**Comment by Bigrome59** [comment] 2020-04-22 06:44
Yes and no anti virus

**Comment by luc1an24** [comment] 2020-04-22 07:30
So "real-time protection" inside "Virus & threat protection settings" is off?
If it is please check "Event Viewer" -> Custom views -> Administrative events and check if there is any "Error" that was caused by NiceHash Miner.

**Comment by luc1an24** [comment] 2020-06-22 08:38
@Bigrome59 
did you manage to fix the issue?
If so please close the issue.
Have a nice day!

**Closed as completed** 2021-04-07 11:22 UTC
