### ISSUE TITLE
cpu does not want to start mining *.19

### ISSUE THREAD

**Issue by techman05** [nicehash/NiceHashMiner#1471] opened 2019-03-24 00:48 UTC
It trys to start but it flashes up on the screen and disappears and comes back. I know its one of the cpu miners since the other have a mining value and it does not. I disabled team red miner on all devices thinking this was the issue since before that I believe I had a screen come up that said "teamredMiner" and it just seemingly sat and showed no activity.

Thanks.

**Comment by S74nk0** [comment] 2019-06-28 13:21
New version released [1.9.1.5](https://github.com/nicehash/NiceHashMinerLegacy/releases/tag/1.9.1.5) closing this issue. If the issue is present in the new release please open a new issue.

Closing.

**Closed as completed by S74nk0** 2019-06-28 13:21 UTC
