### ISSUE TITLE
Profitability down by 30% in comparative of old versions 

### ISSUE THREAD

**Issue by ThiagoSF7** [nicehash/NiceHashMiner#1669] opened 2019-07-12 22:15 UTC
**NOTE this issue tracker is for NiceHashMiner bugs/feature requests ONLY! If you need general help or have a support question related to NHM2 please look at https://www.nicehash.com/support first and open a ticket there if your issue is not specifically NHML related**

For general help there are several community resources available, such as https://reddit.com/r/NiceHash

To keep development of NiceHash Miner streamlined please make sure the following are true before posting an issue:

- Please make requests in English
- The issue has not already been reported.
- **Relevant log files are included (generally `\logs\log.txt`).**
- **The issue is with NHML and not inherent of miner executables.** This can be verified by launching the miner manually and looking for the error.
- **The issue is relevant to NHML specifically and not to the NiceHash service OR NHM2.** (see above)
- Specifications of setup such as NHML version, Windows version, and hardware are included.

Note this is a guide, you can delete this text once you ensure enough information is given

**Comment by X-miner** [comment] 2019-07-13 06:09
On my hand the profitability of my 3 rigs is actually a bit improved, i have 2 RTX 2080Ti 11GB and 1 1080Ti 11GB all 3 on GCuckatoo31

**Comment by S74nk0** [comment] 2019-07-17 12:55
@ThiagoSF7 This is actually related to market/price fluctuation. This is not a bug in the client this just depends what are the buyers willing to pay and currently the profitability may vary because we still have two platforms, some will pay better on the new some on the old one but this has nothing to do with the client itself.

Closing not related to nhm client.

**Closed as completed by S74nk0** 2019-07-17 12:55 UTC
