### ISSUE TITLE
gminer won't close

### ISSUE THREAD

**Issue by jimmyhackers** [nicehash/NiceHashMiner#1427] opened 2019-02-28 18:49 UTC
to elaborate on the title.

g minor isn't closing, i have to x it manually.

clicking stop also doesnt close the gminer algo

**Comment by GOSEF** [comment] 2019-03-01 13:03
Does it look like this?
https://github.com/nicehash/NiceHashMinerLegacy/issues/1420

**Comment by S74nk0** [comment] 2019-03-01 15:23
We have changed GMiner code in the latest release.
https://github.com/nicehash/NiceHashMinerLegacy/releases/tag/1.9.0.17

If the problem is not present in the v1.9.0.17 anymore please close this issue.

**Comment by jimmyhackers** [comment] 2019-03-01 17:40
will do buddy....just gotta spend another hour benchmarking the new version......:P

**Comment by jimmyhackers** [comment] 2019-03-01 22:35
it works so far... good job

**Closed as completed** 2019-03-01 22:35 UTC
