### ISSUE TITLE
my mining company has the following error. how to solve ???

### ISSUE THREAD

**Issue by ronnysanttos** [nicehash/NiceHashMiner#1574] opened 2019-06-26 13:17 UTC
my mining company has the following error. how to solve ???

Phoenix Miner 4.2c Windows/msvc - Release build
-----------------------------------------------

Unknown OpenCL driver version! Hashrate and stale shares may suffer
OpenCL platform: OpenCL 2.0 AMD-APP (2482.5)
Available GPUs for mining:
GPU1: Radeon RX Vega (pcie 5), OpenCL 2.0, 8 GB VRAM, 56 CUs
Eth: the pool list contains 1 pool (1 from command-line)
Eth: primary pool: daggerhashimoto-test.br.nicehash.com:3353
Starting GPU mining
Eth: Connecting to ethash pool daggerhashimoto-test.br.nicehash.com:3353 (proto: Nicehash)
Listening for CDM remote manager at port 4001 in read-only mode
GPU1: 49C 35%
Eth: Can't resolve host daggerhashimoto-test.br.nicehash.com:3353 - Este host nÒo Ú conhecido
Eth: Reconnecting in 20 seconds...
GPU1: 50C 35%
Eth: Connecting to ethash pool daggerhashimoto-test.br.nicehash.com:3353 (proto: Nicehash)
Eth: Can't resolve host daggerhashimoto-test.br.nicehash.com:3353 - Este host nÒo Ú conhecido
Eth: Reconnecting in 20 seconds...

*** 0:00 *** 6/26 09:53 **************************************
Eth: Mining Unknown on >daggerhashimoto-test.br.nicehash.com:3353 for 0:00
Eth: Accepted shares 0 (0 stales), rejected shares 0 (0 stales)
Eth: Incorrect shares 0 (0.00%), est. stales percentage 0.00%
Eth: Average speed (5 min): 0.000 MH/s

**Comment by S74nk0** [comment] 2019-06-28 13:25
Seems to be an issue with closed source miner and maybe your setup.

New version released [1.9.1.5](https://github.com/nicehash/NiceHashMinerLegacy/releases/tag/1.9.1.5) closing this issue. If the issue is present in the new release please open a new issue.

Closing.

**Closed as completed by S74nk0** 2019-06-28 13:25 UTC
