### ISSUE TITLE
Nist efficiency problems

### ISSUE THREAD

**Issue by p1r473** [nicehash/NiceHashMiner#84] opened 2017-07-27 06:28 UTC
Having an issue where Nist is not using much GPU usage, causing low hash rates.
All other algorithms work. 
Works fine on my 2x 1080TI rig but not my 6x 1080TI rig.

![image](https://user-images.githubusercontent.com/9235633/28657036-1da0cf12-7273-11e7-86be-10df3456e926.png)

**Comment by DillonN** [comment] 2017-07-27 07:56
This seems to happen when using many GPUs with Nist5. You can try tweaking `-i <##>` values in the Extra Launch Parameters 

I would also be interested if this happens if the GPUs are split between two miner instances. You could try this by opening a second instance of NHML and having half of the GPUs on each

**Comment by p1r473** [comment] 2017-07-27 16:14
I have no idea what extra launch parameter would fix this

I split cards 1-3 and 4-6 into separate instances and have the same issue

Ignore the colors: I took a screenshot of an RDP session and somehow the colors seem messed up... it looks fine... its not actually red...
![image](https://user-images.githubusercontent.com/9235633/28680720-30395462-72c5-11e7-94f9-5266a84a0f2f.png)

**Comment by p1r473** [comment] 2017-07-27 17:30
Also weird is I enabled Nist for 2 cards, and the other 4 were on a normal algorithm, and I was experiencing the same issue. Not full card usage on ALL cards even when Nist enabled on only 2/6 cards. (Using single instance of NH for this test)

**Comment by p1r473** [comment] 2017-07-31 02:07
What parameters can I pass to the algorithm to fix it?

**Comment by DillonN** [comment] 2017-08-01 19:59
You can pass `-i <##>` to each GPU's extra launch params for Nist5, and put a number around 20 for `<##>`. You can tweak this up or down to see if it helps.

**Comment by p1r473** [comment] 2017-08-07 06:32
What does this parameter do?

**Comment by p1r473** [comment] 2017-08-07 06:39
Is this intensity? What's the default?

**Comment by p1r473** [comment] 2017-08-07 21:05
Seems like -i 25 works on my 6x 1080 TI.. thanks

**Comment by p1r473** [comment] 2017-08-12 15:48
Seems like -i 25 works on my 6x 1080 TI.. thanks
If I go -i 26 i start to get out of memory errors, so 25 is stable!

@DillonN Maybe the default value should be adjusted

**Comment by p1r473** [comment] 2017-08-14 03:31
Seems like -i 25 works on my 6x 1080 TI.. thanks
If I go -i 26 i start to get out of memory errors, so 25 is stable!

@DillonN @nicehashdev Maybe the default value should be adjusted

**Comment by DillonN** [comment] 2017-08-14 08:20
@p1r473 the default value is decided by ccminer and varies per GPU

**Comment by fly16** [comment] 2018-01-01 13:49
the issue isn't resolved by putting an extra flag, ccminer will work on all cards after first time launch, but will only work on 1 to 2 cards after switching from other algos. it seems to always work well when there are 4 cards or less in the rig. i don't think all threads start properly with more than 4 cards.

**Closed as completed** 2018-02-09 21:54 UTC
