### ISSUE TITLE
Miner does not work 

### ISSUE THREAD

**Issue by serh39** [nicehash/NiceHashMiner#945] opened 2018-01-31 04:37 UTC
Miner does not work on the new driver AMD
Please fix the problem in a short time

**Comment by lgwjames** [comment] 2018-01-31 11:09
would be good to post what drivers? most people use blockchain from aug last year

**Comment by serh39** [comment] 2018-02-01 03:52
Driver verison : 18.1.1(adrenalin)

**Comment by Krolow93** [comment] 2018-02-01 09:34
That is a known bug with the latest adrenalin 17.12.1+ drivers
You can read more about it in the [wiki](https://github.com/nicehash/NiceHashMinerLegacy/wiki/AMD-Adrenalin-Drivers-bug)
There is also a temporary workaround under the same [wiki](https://github.com/nicehash/NiceHashMinerLegacy/wiki/AMD-Adrenalin-Drivers-bug) , the wiki also states that it is strongly recommended not to update to these adrenaline drivers.
Even when using the above workaround there is no guarantee that all the miners will work as intended, therefore it is recommended to stick to drivers prior to 17.12.1 until the bug is fixed in the adrenalin drivers

**Comment by serh39** [comment] 2018-02-02 08:33
Okay
Thank you

**Closed as completed** 2019-01-29 10:21 UTC
