### ISSUE TITLE
Stratum error

### ISSUE THREAD

**Issue by GrandMaster64** [nicehash/NiceHashMiner#1353] opened 2018-11-28 02:24 UTC
Geforce gtx 1050, 8 GB ram, Intel(R) Core(TM) i5-7300 HQ CPU @ 2.50 GHz

![screenshot 9](https://user-images.githubusercontent.com/45411111/49124512-bc198d80-f28a-11e8-86b5-cc6cb1562887.png)
![screenshot 12](https://user-images.githubusercontent.com/45411111/49124513-bc198d80-f28a-11e8-8b9c-c89440d10375.png)

I finished setting up the software for my computer, finished benchmarking, and then proceeded to start up the program but for some reason i wasnt able to connect to start mining. I tried changing from the us server to the europe server but had no luck. is there anything i can do? can you guys help in any way? ill attach screenshots

**Comment by angelbbs** [comment] 2018-11-28 22:47
Use nicehash miner legacy fork fix. It contains new and modern miners with failover pools. https://github.com/angelbbs/NiceHashMinerLegacy/releases

**Comment by PBJellytime** [comment] 2018-11-28 22:52
Looks like outward bound connection errors so try turning off any firewalls and AV. Also note that unless you have very cheap electricity you'll be burning more electric than earning at current prices

**Comment by GrandMaster64** [comment] 2018-11-29 18:08
> Use nicehash miner legacy fork fix. It contains new and modern miners with failover pools. https://github.com/angelbbs/NiceHashMinerLegacy/releases

Ok ill give it a try, thanks!

**Comment by GrandMaster64** [comment] 2018-11-29 18:10
> Looks like outward bound connection errors so try turning off any firewalls and AV. Also note that unless you have very cheap electricity you'll be burning more electric than earning at current prices

Electricity isnt an issue, and ill try turning off the windows fire wall and antiviruse. thanks!

**Comment by S74nk0** [comment] 2019-06-28 13:37
New version released [1.9.1.5](https://github.com/nicehash/NiceHashMinerLegacy/releases/tag/1.9.1.5) closing this issue. If the issue is present in the new release please open a new issue.

Closing.

**Closed as completed by S74nk0** 2019-06-28 13:37 UTC
