### ISSUE TITLE
ZHASH GMiner v1.12

### ISSUE THREAD

**Issue by K9Aleksandr** [nicehash/NiceHashMiner#1359] opened 2018-12-23 16:38 UTC
Hello, I ask you to add a miner algorithm ZHASH GMiner CUDA Equihash Miner v1.12 Performance gain up to 30 percent.
https://bitcointalk.org/index.php?topic=5034735.0

**Comment by S74nk0** [comment] 2019-06-28 13:34
New version released [1.9.1.5](https://github.com/nicehash/NiceHashMinerLegacy/releases/tag/1.9.1.5) closing this issue. If the issue is present in the new release please open a new issue.

Closing.

**Closed as completed by S74nk0** 2019-06-28 13:34 UTC
