### ISSUE TITLE
GPU numbering

### ISSUE THREAD

**Issue by STAWKEYE** [nicehash/NiceHashMiner#1525] opened 2019-05-14 15:11 UTC
See image - https://i.imgur.com/2OSQIaz.jpg

Mining rig is 2 x Titan Xp and 3 x Titan V, which do appear in NH main window.

After benchmarking and mining, NH thinks that the Titan Xps are mining on ClaymoreDual and the Titan Vs are on CCMinerTpruvot, however in reality the Titan Xps are not mining at all, and 2 of the 3 Titan V's are dual-mining DaggerHashimoto + x16r which certainly yields poor performance. Independent hardware monitor indicated idle temperatures for Titan Xps even long after DAG is generated and mining has begun.

The mining windows both clearly indicate Titan V's everywhere and so I presume this is an error in the cross-referencing of GPU ID's internal to NiceHash, since both miners are correct in identifying the GPUs they have selected, but wrong in which GPUs "should" have been selected.

**Comment by electricdelicate** [comment] 2019-05-14 16:46
probably the same issue:
https://github.com/nicehash/NiceHashMinerLegacy/issues/1526

**Comment by S74nk0** [comment] 2019-05-20 11:38
There was a mistake in ClaymoreBase plugin. Please try https://github.com/nicehash/NiceHashMinerLegacy/releases/tag/1.9.1.2 and close this issue if the problem is resolved.

**Closed as completed** 2019-05-21 13:12 UTC
