### ISSUE TITLE
Update from 1.9.0.12 to 1.9.0.13 results in: Critical error: missing language

### ISSUE THREAD

**Issue by BensOtz** [nicehash/NiceHashMiner#1386] opened 2019-02-14 14:17 UTC
I made a new map and only copied the configs folder. The exe doesn.t start. This is the log file:
[2019-02-14 15:07:49] [INFO] [NICEHASH] Starting up NiceHashMiner v1.9.0.13
[2019-02-14 15:07:49] [INFO] [NICEHASH] Selected language: English
[2019-02-14 15:07:49] [INFO] [NICEHASH] Critical error: missing language
[2019-02-14 15:07:49] [INFO] [NICEHASH] WMI service seems to be running, ManagementObjectSearcher returned success.

any idees ? there is an en.lang in the lang folder..

**Comment by blacktigersoftware** [comment] 2019-02-17 19:12
bug in code, don't know how it ever worked.  After you get past that, there is another one.  Simple to fix with a debugger.  So just fix it locally.

**Comment by blacktigersoftware** [comment] 2019-02-17 19:17
FYI: In:
international.cs - method Initialize - never returns when it find a matching language
Program.cs - method Main - in startProgram block - program will not start unless your wallet address is not set. !!!!! :) gotta love that.

**Comment by S74nk0** [comment] 2019-06-28 13:32
New version released [1.9.1.5](https://github.com/nicehash/NiceHashMinerLegacy/releases/tag/1.9.1.5) closing this issue. If the issue is present in the new release please open a new issue.

Closing.

**Closed as completed by S74nk0** 2019-06-28 13:32 UTC
