### ISSUE TITLE
XNSUB showing No For X16R and Skunk

### ISSUE THREAD

**Issue by GFreedomX** [nicehash/NiceHashMiner#1452] opened 2019-03-13 03:20 UTC
Hi guys 
i am getting XNSUB showing NO for X16R running on HD7770 and Skunk running on R9 280.
How can i fix it?
I am running on NHML/1.9.0.18

![image](https://user-images.githubusercontent.com/48503005/54251369-f54be400-4581-11e9-870a-75b7ce743e4a.png)

**Comment by GFreedomX** [comment] 2019-03-14 03:56
anyone with any advise on this issue?

**Comment by pardre443** [comment] 2019-03-17 19:57
I DO NOT HAVE THE SLIGHTEST IDEA WHAT I AM DOING...WOULD LIKE YOUR ADVICE?

**Comment by S74nk0** [comment] 2019-06-28 13:22
New version released [1.9.1.5](https://github.com/nicehash/NiceHashMinerLegacy/releases/tag/1.9.1.5) closing this issue. If the issue is present in the new release please open a new issue.

Closing.

**Closed as completed by S74nk0** 2019-06-28 13:22 UTC
