### ISSUE TITLE
NiceHashMinerLegacy Gpu fail

### ISSUE THREAD

**Issue by jonatanjrb** [nicehash/NiceHashMiner#1402] opened 2019-02-19 17:05 UTC
since yesterday the mining by the video card is only at zero and is restarting the hdmi and does not mine anything the cpu is good already updated and I did a new benchmark and at the time of the benchmark works but at the time of mining nothing

**Comment by S74nk0** [comment] 2019-06-28 13:30
New version released [1.9.1.5](https://github.com/nicehash/NiceHashMinerLegacy/releases/tag/1.9.1.5) closing this issue. If the issue is present in the new release please open a new issue.

Closing.

**Closed as completed by S74nk0** 2019-06-28 13:30 UTC
