### ISSUE TITLE
NiceHash 1.9.0.15 Crashing while using more than 7 GPUs

### ISSUE THREAD

**Issue by ismailk1987** [nicehash/NiceHashMiner#1415] opened 2019-02-23 08:39 UTC
My Application is getting crash with Memory errors when I choose more than 7 GPUs, total I have 7 I tried with choosing mix and confirm it is just because of number. I have 8 GB of RAM and allocated 100GB as virtual. Can someone please help 

Cards GTX 1080 ti.

**Comment by S74nk0** [comment] 2019-06-28 13:27
New version released [1.9.1.5](https://github.com/nicehash/NiceHashMinerLegacy/releases/tag/1.9.1.5) closing this issue. If the issue is present in the new release please open a new issue.

Closing.

**Closed as completed by S74nk0** 2019-06-28 13:27 UTC
