### ISSUE TITLE
Run on a schedule?

### ISSUE THREAD

**Issue by sakgoyal** [nicehash/NiceHashMiner#2293] opened 2021-01-21 05:42 UTC
Can we get a feature to implement a set schedule on when to run nicehash? I have a roommate and it gets too loud too sleep at night so being able to automatically stop at midnight and resume at 8am would be a fantastic edition. 
I know there are ways to do it via the task scheduler, but I really want a built in way to do it.

**Comment by MrAlexWeber** [comment] 2021-03-17 01:20
Dupe of #1853

**Closed as completed** 2021-04-29 08:36 UTC
Labels: enhancement
