### ISSUE TITLE
Nicehash choosing wrong card

### ISSUE THREAD

**Issue by YoandyRey** [nicehash/NiceHashMiner#1560] opened 2019-06-17 16:31 UTC
I have a rtx 2060(on pcie 1 8x) and rx 580(on pcie 0 16x) on my rig
I know this could happen: 

If you have mixed GPU system (AMD and NVIDIA cards) do not disable NVIDIA or AMD detection as this will make GMiner and Phoenix choose wrong cards. This is fixed in the Alpha release that you can download from here.

but i have both options enabled and also tried with the Alpha version, no matters what coin i try to mine it is selecting always the rtx 2060 for both miners even if it not supported for that miner/ algo.

tried uninstalling drivers and installing again, switching cards from pcis, 

tried disabling the 2060, nothing, same results, only way to get the 580 mining is unplugging the 2060 from the pci slot.

**Comment by Snarf2948** [comment] 2019-06-17 17:08
I have a RX580 and a 1070Ti.  When both cards are in I BSOD.  Ive taken my 580 out for now and replaced it with a 1050TI and no BSOD for days now.

**Comment by YoandyRey** [comment] 2019-06-17 17:25
@Snarf2948 i had no bsod, two cards work well together, only having issues with nicehash, i could do rendering, gaming at the same time with both gpus, but not mining with nicehash.

**Comment by S74nk0** [comment] 2019-06-18 07:06
@YoandyRey if you are experiencing this issue I assume you are using [1.9.0.23](https://github.com/nicehash/NiceHashMinerLegacy/releases/tag/1.9.0.23) it is noted that this issue is fixed in [1.9.1.4](https://github.com/nicehash/NiceHashMinerLegacy/releases/tag/1.9.1.4) in the release notes. Please use [1.9.1.4](https://github.com/nicehash/NiceHashMinerLegacy/releases/tag/1.9.1.4) as it has many bugfixes including device miner mappings.

**Comment by YoandyRey** [comment] 2019-06-20 00:09
@S74nk0 yes you are right im currently using 1.9.0.23, but also tried with 1.9.1.4 and it keeps firing the nvidia gpu instead od the amd one even when i have only selected the amd gpu.

**Comment by S74nk0** [comment] 2019-06-20 07:42
@YoandyRey Please provide logs where this problem can be confirmed. What Miner is this? ClaymoreDual?

**Comment by S74nk0** [comment] 2019-06-28 13:19
New version released [1.9.1.5](https://github.com/nicehash/NiceHashMinerLegacy/releases/tag/1.9.1.5) closing this issue. If the issue is present in the new release please open a new issue.

Closing.

**Closed as completed by S74nk0** 2019-06-28 13:19 UTC
