### ISSUE TITLE
nhm_windows_1.9.0.17 - Crashes soon after I click on 'I agree' button

### ISSUE THREAD

**Issue by RFB-Ripple** [nicehash/NiceHashMiner#1433] opened 2019-03-02 17:20 UTC
Hello ALL:  
The nhm_windows_1.9.0.17 - Crashes soon after I click on 'I agree' button and the window disappears when it gets to QueryCudaDevices task.  I downloaded V16 and 15.  All have the same result.

 Can ayone help?   Thanks!

[2019-03-02 12:09:55] [INFO] [QueryCPU] QueryCpus START
[2019-03-02 12:09:56] [INFO] [QueryCPU] HyperThreadingEnabled = FALSE
[2019-03-02 12:09:56] [INFO] [QueryCPU] QueryCpus END
[2019-03-02 12:09:56] [INFO] [NvidiaQuery] QueryCudaDevices START
[2019-03-02 12:16:16] [INFO] [NICEHASH] Starting up NiceHashMiner v1.9.0.17
[2019-03-02 12:16:16] [INFO] [NICEHASH] Found language: code: en, name: English
[2019-03-02 12:16:16] [INFO] [NICEHASH] Found language: code: ru, name: Русский
[2019-03-02 12:16:16] [INFO] [NICEHASH] Found language: code: es, name: Español
[2019-03-02 12:16:16] [INFO] [NICEHASH] Found language: code: pt, name: Português
[2019-03-02 12:16:16] [INFO] [NICEHASH] Found language: code: bg, name: Български
[2019-03-02 12:16:16] [INFO] [NICEHASH] Found language: code: it, name: Italiano
[2019-03-02 12:16:16] [INFO] [NICEHASH] Found language: code: pl, name: Polski
[2019-03-02 12:16:16] [INFO] [NICEHASH] Found language: code: zh_cn, name: 简体中文
[2019-03-02 12:16:16] [INFO] [NICEHASH] Found language: code: ro, name: Română
[2019-03-02 12:16:16] [INFO] [NICEHASH] WMI service seems to be running, ManagementObjectSearcher returned success.
[2019-03-02 12:16:16] [INFO] [NICEHASH] Total RAM: 3787MB
[2019-03-02 12:16:16] [INFO] [NICEHASH] Page File Size: 32000MB
[2019-03-02 12:16:16] [INFO] [NICEHASH] Balance update
[2019-03-02 12:16:16] [INFO] [ExtraLaunchParameters] Loading internal params config MinerOptionPackage_ccminer
[2019-03-02 12:16:16] [INFO] [ExtraLaunchParameters] Loading internal params config MinerOptionPackage_ccminer_CryptoNight
[2019-03-02 12:16:16] [INFO] [ExtraLaunchParameters] Loading internal params config MinerOptionPackage_ethminer_OCL
[2019-03-02 12:16:16] [INFO] [ExtraLaunchParameters] Loading internal params config MinerOptionPackage_ethminer_CUDA
[2019-03-02 12:16:16] [INFO] [ExtraLaunchParameters] Loading internal params config MinerOptionPackage_sgminer
[2019-03-02 12:16:16] [INFO] [ExtraLaunchParameters] Loading internal params config MinerOptionPackage_cpuminer_opt
[2019-03-02 12:16:16] [INFO] [ExtraLaunchParameters] Loading internal params config MinerOptionPackage_nheqminer_CPU
[2019-03-02 12:16:16] [INFO] [ExtraLaunchParameters] Loading internal params config MinerOptionPackage_nheqminer_CUDA
[2019-03-02 12:16:16] [INFO] [ExtraLaunchParameters] Loading internal params config MinerOptionPackage_eqm_CUDA
[2019-03-02 12:16:16] [INFO] [ExtraLaunchParameters] Loading internal params config MinerOptionPackage_ClaymoreZcash
[2019-03-02 12:16:16] [INFO] [ExtraLaunchParameters] Loading internal params config MinerOptionPackage_ClaymoreCryptoNight
[2019-03-02 12:16:16] [INFO] [ExtraLaunchParameters] Loading internal params config MinerOptionPackage_OptiminerZcash
[2019-03-02 12:16:16] [INFO] [ExtraLaunchParameters] Loading internal params config MinerOptionPackage_excavator
[2019-03-02 12:16:16] [INFO] [ExtraLaunchParameters] Loading internal params config MinerOptionPackage_ClaymoreDual
[2019-03-02 12:16:16] [INFO] [ExtraLaunchParameters] Loading internal params config MinerOptionPackage_EWBF
[2019-03-02 12:16:16] [INFO] [ExtraLaunchParameters] Loading internal params config MinerOptionPackage_Xmrig
[2019-03-02 12:16:16] [INFO] [ExtraLaunchParameters] Loading internal params config MinerOptionPackage_dtsm
[2019-03-02 12:16:16] [INFO] [ExtraLaunchParameters] Loading internal params config MinerOptionPackage_Phoenix
[2019-03-02 12:16:16] [INFO] [ExtraLaunchParameters] Loading internal params config MinerOptionPackage_GMiner
[2019-03-02 12:16:16] [INFO] [ExtraLaunchParameters] Loading internal params config MinerOptionPackage_BMiner
[2019-03-02 12:16:16] [INFO] [MinerPaths] Loading internal paths config MinerPathPackage_AMD_OpenCL
[2019-03-02 12:16:16] [INFO] [MinerPaths] Loading internal paths config MinerPathPackage_NVIDIA_2_1
[2019-03-02 12:16:16] [INFO] [MinerPaths] Loading internal paths config MinerPathPackage_NVIDIA_3_x
[2019-03-02 12:16:16] [INFO] [MinerPaths] Loading internal paths config MinerPathPackage_NVIDIA_5_x
[2019-03-02 12:16:16] [INFO] [MinerPaths] Loading internal paths config MinerPathPackage_NVIDIA_6_x
[2019-03-02 12:16:20] [INFO] [SystemSpecs] FreePhysicalMemory = 1144352
[2019-03-02 12:16:20] [INFO] [SystemSpecs] FreeVirtualMemory = 26350752
[2019-03-02 12:16:20] [INFO] [SystemSpecs] 
QueryVideoControllers: 
	Win32_VideoController detected:
		Name: NVIDIA GeForce GTX 1080 Ti
		Description: NVIDIA GeForce GTX 1080 Ti
		PNPDeviceID: PCI\VEN_10DE&DEV_1B06&SUBSYS_36021462&REV_A1\4&14EC8C8B&0&00E0
		DriverVersion: 25.21.14.1917
		Status: OK
		InfSection: Section053
		AdapterRAM: 4293918720
	Win32_VideoController detected:
		Name: Intel(R) HD Graphics 610
		Description: Intel(R) HD Graphics 610
		PNPDeviceID: PCI\VEN_8086&DEV_5902&SUBSYS_59021849&REV_04\3&11583659&0&10
		DriverVersion: 25.20.100.6323
		Status: OK
		InfSection: iKBLD_w10_DS
		AdapterRAM: 1073741824
	Win32_VideoController detected:
		Name: NVIDIA GeForce GTX 1080
		Description: NVIDIA GeForce GTX 1080
		PNPDeviceID: PCI\VEN_10DE&DEV_1B80&SUBSYS_33631462&REV_A1\6&18DE1E63&0&000800E9
		DriverVersion: 25.21.14.1917
		Status: OK
		InfSection: Section053
		AdapterRAM: 4293918720
	Win32_VideoController detected:
		Name: NVIDIA GeForce GTX 1080
		Description: NVIDIA GeForce GTX 1080
		PNPDeviceID: PCI\VEN_10DE&DEV_1B80&SUBSYS_142619DA&REV_A1\6&2527380&0&002000E9
		DriverVersion: 25.21.14.1917
		Status: OK
		InfSection: Section053
		AdapterRAM: 4293918720
	Win32_VideoController detected:
		Name: Radeon RX 580 Series
		Description: Radeon RX 580 Series
		PNPDeviceID: PCI\VEN_1002&DEV_67DF&SUBSYS_34171462&REV_E7\4&7D7BB99&0&00E5
		DriverVersion: 25.20.15011.1004
		Status: OK
		InfSection: ati2mtag_Polaris10
		AdapterRAM: 4293918720

[2019-03-02 12:16:20] [INFO] [QueryCPU] QueryCpus START
[2019-03-02 12:16:21] [INFO] [QueryCPU] HyperThreadingEnabled = FALSE
[2019-03-02 12:16:21] [INFO] [QueryCPU] QueryCpus END
[2019-03-02 12:16:21] [INFO] [NvidiaQuery] QueryCudaDevices START

**Comment by S74nk0** [comment] 2019-03-04 09:33
@RFB-Ripple so you have an AMD and NVIDIA mixed rig?

Can you please do the following:
  - Run **check_all_AMD.bat** this will produce **debug_all_out_AMD.txt** file and upload this file here
  - Run **check_all_NVIDIA.bat** this will produce **debug_all_out.txt** file and upload this file here

Try deleting **OpenCL.dll** in the root and run **NiceHashMinerLegacy.exe** and report if it still crashes.

Also do you get an error window or does the program just die?

Files of interest:
![feedback](https://user-images.githubusercontent.com/1517233/53723706-9a6f0a00-3e68-11e9-88ed-b0640715e0e5.PNG)

**Comment by shadytree2266** [comment] 2019-03-04 19:38
the same thing happens to me and this is what pops up

{
   "Platforms": [
       {
           "PlatformNum": 0,
           "PlatformName": "NVIDIA CUDA",
           "Devices": [
               {
                   "DeviceID": 0,
                   "AMD_BUS_ID": -1,
                   "_CL_DEVICE_NAME": "GeForce GTX 1050",
                   "_CL_DEVICE_TYPE": "GPU",
                   "_CL_DEVICE_GLOBAL_MEM_SIZE": 2147483648,
                   "_CL_DEVICE_VENDOR": "NVIDIA Corporation",
                   "_CL_DEVICE_VERSION": "OpenCL 1.2 CUDA",
                   "_CL_DRIVER_VERSION": "398.82",
                   "_CL_DEVICE_BOARD_NAME_AMD": ""
               }
           ]
       }
   ],
   "Status": "OK",
   "ErrorString": ""
}

**Comment by Stregone1** [comment] 2019-03-08 02:14
I am having the same problem. It crashes with no error message or any sort of popup at "Querying CUDA Devices" It crashes after deleting opencl.dll as well.
[debug_all_out_AMD.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/2944127/debug_all_out_AMD.txt)
[debug_all_out.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/2944128/debug_all_out.txt)
[log.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/2944129/log.txt)

**Comment by shadytree2266** [comment] 2019-03-08 02:45
I hope they fix it but I found Honey miner and it works very well

**Comment by Prozzzz** [comment] 2019-03-09 19:48
This is my problem too - and it's now happening with 1.9.0.18 for me.
Any suggestions/solutions would be very much appreciated.

**Comment by RFB-Ripple** [comment] 2019-03-09 20:14
Thank you S74nk0 for your help.  What I ended up doing was uning Display Driver Uninstaller, rebooted my PC and then reinstalled the Nvida drivers.  Then it worked without an issue.
Thanks!

**Comment by Prozzzz** [comment] 2019-03-09 20:18
> Thank you S74nk0 for your help. What I ended up doing was uning Display Driver Uninstaller, rebooted my PC and then reinstalled the Nvida drivers. Then it worked without an issue.
> Thanks!

I've read (and performed) this solution countless times, only with the same problem and logs occurring.
I'll try it this one more time. I'll maybe have to stop Windows Updates from updating the Intel Display drivers before the NVIDIA drivers and see if that works. If it doesn't, then I'm at a loss 😿

**Comment by Prozzzz** [comment] 2019-03-09 21:07
It actually worked!
There may have been two factors that led me to this problem, so I hope my solution can fix this problem for others:
1. Disable Windows Update in services.msc, so Windows doesn't update any on-board graphics drivers.
2. Remove any external display monitors.
3. Use DDU to uninstall NVIDIA drivers, reboot (in Safe Mode again).
4. Use DDU to uninstall on-board graphics drivers.
5. Uninstall and reinstall latest NHML (1.9.0.18) - it should go past the "Querying CUDA devices" part this time and onto the menu.
6. Install NVIDIA drivers.
7. Run NHML again, your NVIDIA GPU should now be on the list.
8. Install on-board graphics drivers through the manufacturer website.

I hope this helps.

**Comment by RFB-Ripple** [comment] 2019-03-09 21:27
This is great.  I'm glad you got this resolved too.  Thanks for the details too  Good too have in case I have a problem later on.  Thanks!

**Comment by DavidVeksler** [comment] 2019-03-13 18:06
This worked for me:

1. Delete "configs" folder
2. Reboot to safe mode
3. Run DDU to uninstall NVIDIA drivers
4. Reboot to normal Windows
5. Install NVIDIA driver

**Comment by Stregone1** [comment] 2019-03-14 16:40
DDU worked. I didn't even try that because this was a minutes old windows install and AFAIK you can't reboot into safemode over teamviewer. Finally got desperate and hooked up a monitor and keyboard and tried it.

**Comment by S74nk0** [comment] 2019-03-29 12:52
This issue should be fixed with the current [release-1.9.0.20](https://github.com/nicehash/NiceHashMinerLegacy/releases/tag/1.9.0.20).
This issue was caused by **NVIDIA DCH drivers**.

Reopen issue if it is still present.

**Closed as completed by S74nk0** 2019-03-29 12:52 UTC
