### ISSUE TITLE
Reduced hashrate across the board

### ISSUE THREAD

**Issue by ne0rrmatrix** [nicehash/NiceHashMiner#1580] opened 2019-06-29 02:52 UTC
I downloaded latest stable client 1.9.15 and it had lower hashrates for both nvidia and amd cards across two machines. It appeared the OC i had on nvdia combined with ethenlargement pill loaded resulted in  Nvidia 1080ti averaging 31MH's and i had on previous client been getting 49 to 51 overall. Also the other algo's had hashrates drop by more than 40 percent.

On AMD system the algo's were across the board just flat out different and lower in a very meaningful way. About a 50 to 60 percent drop in performance. Will be staying on previous client till i figure out what is going on. 

I am running ethenlargment pill process manually. I am running an OC using afterburner manually. Issue is most likely user error. I switched back to older client and everything returned to normal on both AMD and Nvidia systems.

**Comment by Maas1337** [comment] 2019-06-29 15:02
Got the same Thing.... When i benchmark, after a few benches the power Limit of all gpus is set to 49% instead of 100%. Switched to..  1.9.0.23

**Comment by X-miner** [comment] 2019-06-29 22:46
How can we fix this shit? Cause i switched back to 1.9.0.23 and it does the same.

**Comment by boldheart007** [comment] 2019-06-30 03:20
Still same whatever tried restarting
Locked msi afterburner profiles
After every restart should load msi afterburner profile manually

**Comment by S74nk0** [comment] 2019-06-30 08:52
Duplicate issue please read response https://github.com/nicehash/NiceHashMinerLegacy/issues/1583#issuecomment-507019255

**Comment by S74nk0** [comment] 2019-06-30 08:54
@ne0rrmatrix What algorithms on AMD? AMD doesn't have any power settings from NHML.

**Comment by Maas1337** [comment] 2019-07-01 11:00
Fixxed for me! Thanks for the fast support! Great job!

**Comment by ne0rrmatrix** [comment] 2019-07-01 12:43
S74nk0 AMD works with new updated version that you posted. No issues with AMD ATM. 

Nvidia is working well with update too. BTW i have to start afterburner after starting nicehash as it seems to mess with custom OC from afterburner. It all works fine as long as i set afterburner after i launch nicehash though. If i start nicehash after setting OC in afterburner it goes away and i have to click profile and set it again.

**Comment by S74nk0** [comment] 2019-07-02 10:58
Duplicate of https://github.com/nicehash/NiceHashMinerLegacy/issues/1583

**Closed as completed by S74nk0** 2019-07-02 10:58 UTC
