### ISSUE TITLE
RX480 not detected, only my CPU i7-7700k

### ISSUE THREAD

**Issue by Defalt100** [nicehash/NiceHashMiner#748] opened 2017-12-21 16:22 UTC
To keep development of NiceHash Miner Legacy streamlined please make sure the following are true before posting an issue:

- Please make requests in English
- The issue has not already been reported.
- Relevant log files are included (generally `\logs\log.txt`).
- The issue is with NHML and not inherent of miner executables. This can be verified by launching the miner manually and looking for the error.
- The issue is relevant to NHML specifically and not to the NiceHash service.
- Specifications of setup such as NHML version, Windows version, and hardware are included.

Note this is a guide, you can delete this text once you ensure enough information is given

**Comment by SK1NN3RSA** [comment] 2017-12-21 17:36
I have the exact same issue and nicehash requested that i go look for help here so if the dev team working on nicehashminerlegacy could please fix this we would very much appreciated.
running two different computers
computer 1:
windows 7 ultimate 64bit
12gb ram
intel core i7 cpu 3.2ghz
gpu amd rx480 8gb

computer 2:
windows 10
16gb ram
intel core i7 cpu 3.4ghz
gpu amd rx480 8gb

**Comment by endlessterror** [comment] 2017-12-21 17:41
Seems to be a duplicate of Check the bugs first people! 

Possible duplicate of bug #1373

**Comment by Palidan17** [comment] 2017-12-21 23:05
I have the same issue. Intel i7 7700 is dtected but not my amd rx 570 4gb. Is there anything i can do to fix it?

**Comment by AlienUrineSampl** [comment] 2017-12-22 00:23
Revert your GPU's back to Crimson drivers. Adrenaline drivers are not being detected.

**Comment by S74nk0** [comment] 2019-07-02 14:46
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.

**Closed as completed by S74nk0** 2019-07-02 14:46 UTC
