### ISSUE TITLE
Nicehash Legacy Miner 1.9.0.15

### ISSUE THREAD

**Issue by pedrojs-sapo** [nicehash/NiceHashMiner#1413] opened 2019-02-22 18:21 UTC
Nicehash changing card OC Settings probably when restarting miner. 
The first GPU (1080Ti or 1070 - 2 different RIGs) on the RIG get OC changed by Nicehash.
Nicehash V2 also had the same problem but it was solved on the last released version.
This "bug" can shutdown the RIG if the Power Supply can't handle more than the Power
defined in the OC settings.

**Comment by wxprofessor** [comment] 2019-02-23 02:10
Is there a setting in the configs to disable that? I notice a:

`"DisableAMDTempControl": true,`

in General.json ... does that apply for Nvidia too? i.e. there is no Nvidia temp control option in the config 🤔

**Comment by pedrojs-sapo** [comment] 2019-02-26 08:07
I really don't know. But why only the 1st GPU in each RIG? 
Why the Power set to 100% TDP, and why did Nicehash V2 (to be discontinued) had the same "bug" (with all my RIGS) till the last launched version and it was solved.

**Comment by S74nk0** [comment] 2019-06-28 13:28
New version released [1.9.1.5](https://github.com/nicehash/NiceHashMinerLegacy/releases/tag/1.9.1.5) closing this issue. If the issue is present in the new release please open a new issue.

Closing.

**Closed as completed by S74nk0** 2019-06-28 13:28 UTC
