### ISSUE TITLE
NHM 1.9.2.6 Cannot benchmark

### ISSUE THREAD

**Issue by fritzr4** [nicehash/NiceHashMiner#1646] opened 2019-07-07 01:26 UTC
Benchmark appears to run normally.  Some algorithms finish without error, some fail.
The Speed entry is updated with a speed by benchmark
The Ratio BTC/GH and BTC/Day remain unchanged when the benchmark completes.
With the "Start mining after benchmark" checked, NiceHashMiner will start when benchmarking is complete and immediately stop with a status of "Error" for all selected GPUs

Possibly related:  NHM does not request login credentials for Nicehash.com & leaves the BTC address field blank when first run. [already subject of another bug report]
Dashboard similarly is unaware of NHM 1.9.2.6 even when the BTC address is correctly filled in (copy & paste from stats page)

This behavior is repeatable across machines and with freshly downloaded files.
Currently using Win10 with GTX 1660 and GTX 1080 GPUs.

**Comment by BobJuch** [comment] 2019-07-08 16:38
I get the same problem on 1.9.2.7.

**Comment by tusharantal** [comment] 2019-07-08 18:23
I am also facing the same problem... I am using powercolour red dragon rx570 cards..

**Comment by seso1129** [comment] 2019-07-10 04:33
The same problem with 1.9.2.7 for 1080 GPU!

**Comment by vasyapupkin1** [comment] 2019-07-10 16:12
...because some miners are not working properly or current algo doesn't support your card or some specific error or miner can use wrong card. For example:
![001](https://user-images.githubusercontent.com/29598026/60985679-8bccbe00-a346-11e9-99e9-4e7e96e09b4e.jpg)
![002](https://user-images.githubusercontent.com/29598026/60985681-8bccbe00-a346-11e9-826a-96604f6978d5.jpg)
try manually

**Comment by BobJuch** [comment] 2019-07-10 16:15
No, the problem is not with a miner; none of the benchmarks work.

**Comment by vasyapupkin1** [comment] 2019-07-10 16:57
Maby some pics and/or logs explains more?

**Comment by seso1129** [comment] 2019-07-11 09:22
@vasyapupkin1 see #1656

**Comment by BobJuch** [comment] 2019-07-11 12:51
That's not my problem. All the benchmarks complete but the Ratio and BTC columns are zero.

**Comment by zeta009** [comment] 2019-07-11 13:22
try this stratum. stratum+tcp://stratum.bitcoin.cz port:3333

**Comment by S74nk0** [comment] 2019-07-17 13:43
Issue/Issues related to back-end. Back-end issues are resolved. 

Closing

**Closed as completed by S74nk0** 2019-07-17 13:43 UTC
