### ISSUE TITLE
Multiple cmd windows, stuck, not mining

### ISSUE THREAD

**Issue by Xuchilbara** [nicehash/NiceHashMiner#1548] opened 2019-05-31 20:30 UTC
Hello,

I noticed a critical bug on NiceHash. When I clic Start, sometimes it seems to be starting mining whent the cmd window appears, but then a lot of cmd windows start coming, all the Windows resources are used (CPU and all that, it gets almost freezed) and it just doesn't mine a thing.

Even sometimes all the cmd windows each give an error popup saying There's no disk on device D: or something the like.

This problem is very inconvenient since I already lost (or not earned) a lot of crypto because I thought it was mining for hours when it was stuck just there.

I'm using the latest version and this has been happening for two or three versions already.

I hope I'm not alone and this serious issue is fixed soon already.

Thanks.

**Comment by yearight** [comment] 2019-06-01 18:29
For me version 1.9.0.22 only. 
I went back to .21, which the app says is 2x as profitable as well.
I my case my browser slowed to a crawl, and when I checked task manager I noticed all the windows and ended tasks.

**Comment by S74nk0** [comment] 2019-06-04 10:09
@Xuchilbara Can you please specify the exact version number of NHML?

**Comment by S74nk0** [comment] 2019-06-04 11:01
@yearight One miner version cannot be 2x profitable since the miners code is almost identical and the miner binaries are for the most part identical or faster than the ones in previous releases. Since most miners require online benchmarks this depends on the order your miner got. This will be changed/fixed in one of the upcoming releases where benchmarks will be executed locally on a dummy stratum that will be deterministic and will yield stable results unlike now.

**Comment by yearight** [comment] 2019-06-04 13:40
Thanks for the response, I never did look at what the website reports, that's why I mentioned the app only. I never ran .22 long enough to look as I have the same problem as the OP. 
The miners code might be identical but the Nicehash app is the middle man isn't it? AS the other guy in your link posted, the app is the only change not the miner.

**Comment by Xuchilbara** [comment] 2019-06-04 15:47
> 
> 
> @Xuchilbara Can you please specify the exact version number of NHML?

It's the latest one, 1.9.0.22, happening since a couple of versions prior as I said.

I think it was nbminer.exe the miner that failed the last time.

Thanks for the answers!

**Comment by Xuchilbara** [comment] 2019-06-09 21:17
Downloaded and installed the latest release, 1.9.0.23, now EVERY time opens two or three WORKING cmd windows at the same time, when I leave it mining for several minutes.

Which is worrying because it shows very low USD/day, so I guess my computer is working double or triple for nothing (counting electricity costs).

Hope I'm not the only one and it gets fixed soon.

**Comment by scott1188** [comment] 2019-06-20 12:02
im also having same issue,, fresh install the windows, latest amd driver and latest miner, the hash rate is only half of the normal.

**Comment by S74nk0** [comment] 2019-06-28 13:20
New version released [1.9.1.5](https://github.com/nicehash/NiceHashMinerLegacy/releases/tag/1.9.1.5) closing this issue. If the issue is present in the new release please open a new issue.

Closing.

**Closed as completed by S74nk0** 2019-06-28 13:20 UTC
