### ISSUE TITLE
benchmark

### ISSUE THREAD

**Issue by rustemkerrim** [nicehash/NiceHashMiner#1461] opened 2019-03-16 21:16 UTC
I can't bechmark on windows 10 64 bit , when i try it , nhm is closing then gminer's miner.exe is working at the back

**Comment by S74nk0** [comment] 2019-06-28 13:30
New version released [1.9.1.5](https://github.com/nicehash/NiceHashMinerLegacy/releases/tag/1.9.1.5) closing this issue. If the issue is present in the new release please open a new issue.

Closing.

**Closed as completed by S74nk0** 2019-06-28 13:30 UTC
