### ISSUE TITLE
Bug: 1.9.0.18 runs okay for a while, then puts system to sleep

### ISSUE THREAD

**Issue by rvail623** [nicehash/NiceHashMiner#1444] opened 2019-03-10 17:34 UTC
**NOTE this issue tracker is for NiceHashMinerLegacy bugs/feature requests ONLY! If you need general help or have a support question related to NHM2 please look at https://www.nicehash.com/support first and open a ticket there if your issue is not specifically NHML related**

For general help there are several community resources available, such as https://reddit.com/r/NiceHash

To keep development of NiceHash Miner Legacy streamlined please make sure the following are true before posting an issue:

- Please make requests in English
- The issue has not already been reported.
- **Relevant log files are included (generally `\logs\log.txt`).**
- **The issue is with NHML and not inherent of miner executables.** This can be verified by launching the miner manually and looking for the error.
- **The issue is relevant to NHML specifically and not to the NiceHash service OR NHM2.** (see above)
- Specifications of setup such as NHML version, Windows version, and hardware are included.

Note this is a guide, you can delete this text once you ensure enough information is given

**Comment by rvail623** [comment] 2019-03-10 17:41
Windows 10 64-bit [Version 10.0.17763.348] on an Intel Z87 machine with 8 Gb memory & with 2x GTX 1070Ti + 1x GTX 1060 running Nicehash 1.9.0.18. System runs for several hours okay, then randomly shuts down to sleep mode. There was an error notice about lack of virtual memory, so switched from Windows managed to a set amount of 32 Gb virtual memory. Otherwise, the system is unchanged from previous versions of Nicehash, which all ran fine for 24 hours/day. 

Another machine with 1x Radeon Vega 56 card runs fine, without problem. So: it seems limited to nVidia cards. 
Note: tried uploading the log.txt file, but keep getting "Something went really wrong, and we can't process that file. Try again."

**Comment by S74nk0** [comment] 2019-06-28 13:22
New version released [1.9.1.5](https://github.com/nicehash/NiceHashMinerLegacy/releases/tag/1.9.1.5) closing this issue. If the issue is present in the new release please open a new issue.

Closing.

**Closed as completed by S74nk0** 2019-06-28 13:22 UTC
