### ISSUE TITLE
BTC projected earnings per day may be inaccurate 

### ISSUE THREAD

**Issue by i-w-e-e-d** [nicehash/NiceHashMiner#1512] opened 2019-04-22 18:59 UTC
This may be an issue  that i'm exclusively experiencing with my hand made mining rigs... regardless my confirmed/ paid earnings for the past 2 months are double(2x) than the declared price per day rate advertised on the NiceHashMinerLegacy v1.9.0.19/20 app. Im not sure if the app is utilizing the Bitpay api for these stats , however it seems like the issue is the definition of "Per Day". Is it possible that that the projected earnings are defined as a 12 hour "Day" rather than a 24 hour "day"?

Anyways if other people are experiencing the same issue, it would be of huge benefit for NiceHash to advertise the projected amount in a 24 hr day format :)

**Comment by S74nk0** [comment] 2019-06-28 13:25
New version released [1.9.1.5](https://github.com/nicehash/NiceHashMinerLegacy/releases/tag/1.9.1.5) closing this issue. If the issue is present in the new release please open a new issue.

Closing.

**Closed as completed by S74nk0** 2019-06-28 13:25 UTC
