### ISSUE TITLE
intel+amd wrong platform setting. (XmrStak)

### ISSUE THREAD

**Issue by Rakly3** [nicehash/NiceHashMiner#1554] opened 2019-06-08 12:35 UTC
Can't use xmrStak because NHM sets the platform to 0 while it has to be 1.
Error CL_INVALID_KERNEL

**Comment by S74nk0** [comment] 2019-06-28 13:19
New version released [1.9.1.5](https://github.com/nicehash/NiceHashMinerLegacy/releases/tag/1.9.1.5) closing this issue. If the issue is present in the new release please open a new issue.

Closing.

**Closed as completed by S74nk0** 2019-06-28 13:19 UTC

**Comment by GeF0rs** [comment] 2019-06-30 20:34
![image](https://user-images.githubusercontent.com/18257294/60401836-c472d780-9b8f-11e9-9762-5bb4608c2d6d.png)

Version 1.9.1.5, Error
