### ISSUE TITLE
Unable to run benchmark precise

### ISSUE THREAD

**Issue by Cazs03** [nicehash/NiceHashMiner#1460] opened 2019-03-15 17:17 UTC
```
[2019-03-15 17:56:44] [INFO] [NVML] System.Exception: NVML get load failed with code: GPUIsLost
   en NiceHashMiner.Devices.CudaComputeDevice.get_Load()
[2019-03-15 17:56:44] [INFO] [NVML] System.Exception: NVML power get failed with status: GPUIsLost
   en NiceHashMiner.Devices.CudaComputeDevice.get_PowerUsage()
```
Version 1.9.0.19
Is imposible run benchmark 
What is it?

**Comment by S74nk0** [comment] 2019-06-28 13:22
New version released [1.9.1.5](https://github.com/nicehash/NiceHashMinerLegacy/releases/tag/1.9.1.5) closing this issue. If the issue is present in the new release please open a new issue.

Closing.

**Closed as completed by S74nk0** 2019-06-28 13:22 UTC
