### ISSUE TITLE
ccminer - application error. The Instruction at 0x referenced memory. Memory could not be written.

### ISSUE THREAD

**Issue by mayamak** [nicehash/NiceHashMiner#1421] opened 2019-02-24 12:10 UTC
NiceHash Legacy stopped working with below error 
"The Instruction at 0x... referenced memory at 0x... The memory could not written"
screenshot of error https://i.imgur.com/SfwL7z5.png

**Comment by TimRoe** [comment] 2019-02-24 23:14
Just chiming in with more details.

Computer hard crashed yesterday awhile after switching over to Legacy and I think once (maybe twice?) overnight. Keeping an eye on it today, I'm pretty sure it was mining with ccminer.

There's a pretty hardcore memory leak. I let it run and was keeping an eye on my memory. After a few hours, the Nicehash Legacy process was using the entirety of my remaining 10 GB of RAM (other processes using 5~6 GB). I then pulled up perfmon to track the usage of my paging file since it was clearly going to disk. That got up to 50% before my screens went black for about 45 seconds (was about to hard reboot before they came to and I could stop the mining)--my page file (maybe partially from the crashing) appears to be auto allocating 26 GB of space.

So, ccminer was using 23GB of RAM (including page file).

For comparison, it was using gminer once I started it back up--which was humming along at 26.8 MB of RAM usage. 

It just switched back over to ccminer a few minutes ago, already up to 219 MB of RAM usage. Keeping an eye on it for the last 10~15 minutes, it looks to just keep slowing climbing in RAM usage. Not sure what might cause jumps in RAM usage, but I assume there must be since it definitely wasn't running too long before I started watching and got to that 219 MB RAM.

**Comment by InstantAli3n** [comment] 2019-03-06 02:18
Same error as OP.  Looks like a memory leak, RAM goes from 3.3GB to 10.5GB over a minute or two with a single thread at 100%. I turned on the screen on to check and closed NHminer at that point.

Logs show at some point my memory usage and pagefile/commit were maxed out at 16 and 32 GB respectively.

Looks like it was mining MTP at the time.

**Comment by S74nk0** [comment] 2019-06-28 13:27
New version released [1.9.1.5](https://github.com/nicehash/NiceHashMinerLegacy/releases/tag/1.9.1.5) closing this issue. If the issue is present in the new release please open a new issue.

Closing.

**Closed as completed by S74nk0** 2019-06-28 13:27 UTC
