### ISSUE TITLE
System.Exception getting Temp and Load

### ISSUE THREAD

**Issue by pedrojs-sapo** [nicehash/NiceHashMiner#1498] opened 2019-04-15 09:26 UTC
Hi

I have 6 ASUS 1080 Ti running on Windows 10.
I'm getting lots of these errors:

"[10:21:20] [NVML] System.Exception: NVML get load failed with code: Unknown
   em NiceHashMiner.Devices.CudaComputeDevice.get_Load()
   
[10:23:20] [NVML] System.Exception: NVML get temp failed with code: Unknown
   em NiceHashMiner.Devices.CudaComputeDevice.get_Temp()
"

Any idea? D you need or want more info?

Thanks

Regards

PJS

**Comment by dimon4ik2203** [comment] 2019-04-18 23:09
> Привет
> 
> У меня 6 ASUS 1080 Ti работает на Windows 10. 
> Я получаю много этих ошибок:
> 
> "[10:21:20] [NVML] System.Exception: ошибка загрузки NVML с кодом: Unknown 
> em NiceHashMiner.Devices.CudaComputeDevice.get_Load ()
> 
> [10:23:20] [NVML] System.Exception: ошибка получения временного значения NVML с кодом: Unknown 
> em NiceHashMiner.Devices.CudaComputeDevice.get_Temp () 
> "
> 
> Любая идея? Вам нужно или хотите больше информации?
> 
> Спасибо
> 
> С уважением
> 
> PJS

**Comment by S74nk0** [comment] 2019-06-28 13:21
New version released [1.9.1.5](https://github.com/nicehash/NiceHashMinerLegacy/releases/tag/1.9.1.5) closing this issue. If the issue is present in the new release please open a new issue.

Closing.

**Closed as completed by S74nk0** 2019-06-28 13:21 UTC
