### ISSUE TITLE
1.8.1.3 Not taking the device ticking into account

### ISSUE THREAD

**Issue by ydem** [nicehash/NiceHashMiner#320] opened 2017-09-15 21:11 UTC
Hey, I just installed the latest release of 1.8.1.3, but had to revert back to 1.8.1.2

The reason is i have two gpus 1070 for mining + 970 as the main display card, when i tick 1070 only and click start the 970 main gpu also stutters in a crazy way, the mouse barely moves when the dualclaymore is mining, never had this issue before...

So after reverting back to 1.8.1.2 every works correctly again, i was using the same configuration on both versions.

I'm guessing both cards start mining no matter what i tick? or is it something else?

**Comment by TheSorrow1** [comment] 2017-09-16 17:04
The issue is not from you, What you can do is to use a older driver in case its critical for you to see the temps/fan speed, you can also use programs such as MSI afterburner to view that as well.

This has to do with the claymore GPU XMR miner, and not nicehash legacy itself. Claymore has replied that he will release a new version of his XMR miner in a week or so with fixed detection of fan and
temperatures and a 5% increase on most cards. Once that is out you can copy it into the bin folder of nicehash legacy and replace the old one or wait for legacy to include it.

Best regards
The Sorrow

**Comment by DillonN** [comment] 2017-09-19 12:05
How did you install 1.8.1.3? Indexing changed for ClaymoreDual so if the bins are not updated you will get this issue. If you still have a problem could you post your log.txt file

**Comment by ydem** [comment] 2017-09-19 13:44
You are right, my bad, i installed the latest version on top of the previous version's folder which messed it up, i wanted to avoid doing a fresh folder for every update (to avoid the time consuming benchmark process), but it works now on a fresh folder as intended.

A reminder to anyone trying to overwrite a version above a previous one, it doesn't always work.

You can close this issue and maybe add a note that you need to install it on a fresh folder if things changed a lot between versions, thanks for your help.

Another thing i forgot : this is the first version where i don't see the message on 1.8.1.2 that a 'new version 1.8.1.3 is ready for update'

**Comment by ChriscomIT** [comment] 2017-09-19 20:09
I advise you to just download the new version unzip it and let it download the updated bins and then you close it. After that go to your old NiceHash folder copy over the benchmark and general (benchmark-GEN/GPU.json + General.json) config files to the configs folder of the new version and run the new version. That way you are always good to go and you just need to benchmark new algorithms if one or more were added.

**Comment by ydem** [comment] 2017-09-19 21:39
Forgot there is a separate config folder in there, i'll keep note for another release, thanks.

**Closed as completed** 2018-02-11 03:07 UTC
