### ISSUE TITLE
Freeze or not mining...

### ISSUE THREAD

**Issue by gbdb** [nicehash/NiceHashMiner#635] opened 2017-11-20 15:35 UTC
Hello,

New to mining here! sorry for possible mistakes.

I got two exact same setup one is working non-stop since day one (about a week ago) but the other keep making a lot of trouble.

Here is the setup;

- Windows 10
- 1200w
- GA-H110-D3A-rev-10  ( Bios F23A ) 
         (( could it be some minor BIOS setting differences ? )) 
          I had issues with the ''mining'' option on the board. when enabled it wont post. 
         and it's not enabled on the working machine.. so I doubt..
- RX580 8Gb x 6 
- 4Gb RAM + Intel G4400

[log.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/1488134/log.txt)

it will freeze, stop mining, report a card SICK( GPU 0), go Offline ( I then get email notification), or HashRate simply drop to zero.

I just updated the video card driver to the 17.11.1 and see if it works better.. but the miner take a few minutes to start, then go off line, buy the time I walk away I get the notification on my phone. 

any Ideas ? or suggestions ? 

I even made a clean system image of the working one, and used it on a different SSD to be sure.
the only difference would be the possible defective risers (witch looks all visually OK, and good quality solder)

please help

**Comment by DillonN** [comment] 2017-11-21 12:19
For some reason it looks as though NHML is unable to communicate with sgminer. This can be caused by a number of reasons, if the problem is a hardware one then it is beyond the scope of this forum but you should rule that out first. 

If NHML detects 0 speed it will attempt to restart the miner. If the miner is not working properly, then NHML is unable to close it but will open up a new one still, this can lead to system instability if many are opened. If you are seeing many miner windows open you can disable this functionality by editing `configs/General.json` and turning off the cooldown checker. 

Also if you are only getting this problem with sgminer_cryptonight a workaround could be to simply disable that algorithm

**Comment by spock9** [comment] 2017-11-25 02:42
how do you disable a specific algorithm?

**Comment by DillonN** [comment] 2017-12-01 00:12
Just uncheck it in the benchmark list

**Closed as completed** 2018-02-19 05:01 UTC
