### ISSUE TITLE
PhoenixMiner and ethDCRminer are both mining eth

### ISSUE THREAD

**Issue by techman05** [nicehash/NiceHashMiner#1384] opened 2019-02-13 22:04 UTC
Seem like a waste to have both mining the same coin. Hopefully theres some way to tell the nicehash legacy miner to notice this and have both mine together?.

This is 1.9.0.12 nice hash miner legacy.

Thanks

**Comment by S74nk0** [comment] 2019-06-28 13:33
New version released [1.9.1.5](https://github.com/nicehash/NiceHashMinerLegacy/releases/tag/1.9.1.5) closing this issue. If the issue is present in the new release please open a new issue.

Closing.

**Closed as completed by S74nk0** 2019-06-28 13:33 UTC
