### ISSUE TITLE
not working windows 7

### ISSUE THREAD

**Issue by senthil1975** [nicehash/NiceHashMiner#1960] opened 2020-02-01 15:44 UTC
**NOTE this issue tracker is for NiceHashMiner bugs/feature requests ONLY! If you need general help or have a support question related to NHM2 (OBSOLETE) or NHOS please look at https://www.nicehash.com/support first and open a ticket there if your issue is not specifically NHM related**

For general help there are several community resources available, such as https://reddit.com/r/NiceHash

There is a [documentation](https://github.com/nicehash/NiceHashMiner/tree/master/doc) available, so please check it out first. If you don't find the answer there, please create a new issue, that follows requirements stated below. 

To keep development of NiceHash Miner streamlined please make sure the following are true before posting an issue:

- Please make requests in English
- The issue has not already been reported.
- **Relevant log files are included (generally `\logs\log.txt`).**
- **The issue is with NHM and not inherent of miner executables.** This can be verified by launching the miner manually and looking for the error.
- **The issue is relevant to NHM specifically and not to the NiceHash service, NHOS or NHM2.** (see above)
- Specifications of setup such as NHM version, Windows version, and hardware are included.

Note this is a guide, you can delete this text once you ensure enough information is given

**Comment by almartins** [comment] 2020-02-01 18:40
Same here, Windows 7 64 bits; 
Log:
[2020-02-01 18:36:39] [INFO] [NICEHASH] Starting up NiceHash Miner v3.0.0.3
[2020-02-01 18:36:39] [INFO] [Translations] Found language: code: en, name: English
[2020-02-01 18:36:39] [INFO] [Translations] Found language: code: ru, name: Русский (Unofficial)
[2020-02-01 18:36:39] [INFO] [Translations] Found language: code: es, name: Español (Unofficial)
[2020-02-01 18:36:39] [INFO] [Translations] Found language: code: pt, name: Português (Unofficial)
[2020-02-01 18:36:39] [INFO] [Translations] Found language: code: bg, name: Български (Unofficial)
[2020-02-01 18:36:39] [INFO] [Translations] Found language: code: it, name: Italiano (Unofficial)
[2020-02-01 18:36:39] [INFO] [Translations] Found language: code: pl, name: Polski (Unofficial)
[2020-02-01 18:36:39] [INFO] [Translations] Found language: code: zh_cn, name: 简体中文 (Unofficial)
[2020-02-01 18:36:39] [INFO] [Translations] Found language: code: ro, name: Română (Unofficial)
[2020-02-01 18:36:39] [INFO] [SystemSpecs] WMI service seems to be running, ManagementObjectSearcher returned success.

**Comment by techman05** [comment] 2020-02-02 01:55
Seems me as well. Asks me to verify eula and 3rd party and then nothing. Had no virus warning popups.

btw I used the updater and not the zip file

**Comment by sbkbg** [comment] 2020-02-02 20:34
Same here :

Problem signature:
  Problem Event Name:	CLR20r3
  Problem Signature 01:	NiceHashMiner.exe
  Problem Signature 02:	3.0.0.3
  Problem Signature 03:	f9955a67
  Problem Signature 04:	mscorlib
  Problem Signature 05:	4.7.3062.0
  Problem Signature 06:	5ab95381
  Problem Signature 07:	4286
  Problem Signature 08:	a4
  Problem Signature 09:	System.Windows.Markup.XamlParse
  OS Version:	6.1.7601.2.1.0.256.48
  Locale ID:	1026
  Additional Information 1:	d176
  Additional Information 2:	d1764c47aa602b9dd4ea57eee9fc1fdf
  Additional Information 3:	1c20
  Additional Information 4:	1c2025bdc81ba1496ba852e6e75691ec

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0409

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt

**Comment by S74nk0** [comment] 2020-02-03 09:22
Please make sure that you have  https://dotnet.microsoft.com/download/dotnet-framework 4.7.2 or 4.8 installed. 

Close this issue if framework installation fixes your problem.

**Comment by techman05** [comment] 2020-02-03 09:53
I have no furthur updates listed for windows 7. If a framework "was" missing due to changes should'nt it be packaged with the installer/update.

**Comment by sbkbg** [comment] 2020-02-03 11:00
> Please make sure that you have https://dotnet.microsoft.com/download/dotnet-framework 4.7.2 or 4.8 installed.
> 
> Close this issue if framework installation fixes your problem.

I've installed 4.8 , restarted, uninstalled nicehash , restarted again, downloaded fresh nicehash and installed it :)  STILL NOT WORKING -  

Problem signature:
  Problem Event Name:	CLR20r3
  Problem Signature 01:	NiceHashMiner.exe
  Problem Signature 02:	3.0.0.3
  Problem Signature 03:	f9955a67
  Problem Signature 04:	mscorlib
  Problem Signature 05:	4.8.3928.0
  Problem Signature 06:	5d3900b3
  Problem Signature 07:	42d0
  Problem Signature 08:	a4
  Problem Signature 09:	System.Windows.Markup.XamlParse
  OS Version:	6.1.7601.2.1.0.256.48
  Locale ID:	1026
  Additional Information 1:	50eb
  Additional Information 2:	50eb1713140587a1def74311a8a80149
  Additional Information 3:	f0db
  Additional Information 4:	f0db14efaa12db8098fb0e1ede7d90e7

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0409

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt

**Comment by S74nk0** [comment] 2020-02-03 13:28
If the .NET framework doesn't help I was obviously mistaken. 
I have prepared another build that uses a different Theme library. Seems that the released version doesn't work on most Windows 7 systems. 
Please try out this build. If this fixes Windows 7 issue, we will release it with the older library. 
https://github.com/nicehash/NiceHashMiner/releases/download/3.0.0.3/nhm_windows_3.0.0.3_net45_aero1.zip

**Comment by S74nk0** [comment] 2020-02-03 14:51
Please try https://github.com/nicehash/NiceHashMiner/releases/tag/3.0.0.4 for Windows 7. This version should be compatible with Windows 7.

Please close this issue if the problem is resolved.

**Comment by sbkbg** [comment] 2020-02-03 16:21
> Please try https://github.com/nicehash/NiceHashMiner/releases/tag/3.0.0.4 for Windows 7. This version should be compatible with Windows 7.
> 
> Please close this issue if the problem is resolved.

Yes It is WORKING NOW :) :) :)

**Closed as completed** 2020-02-03 18:10 UTC
