### ISSUE TITLE
NHM 3.0.5.5  auto update bug

### ISSUE THREAD

**Issue by EvgeniyKorepov** [nicehash/NiceHashMiner#2237] opened 2020-12-10 17:21 UTC
![image](https://user-images.githubusercontent.com/35364901/101806669-4efd8b80-3b25-11eb-9b7e-2c033adb686f.png)

**Comment by EvgeniyKorepov** [comment] 2020-12-10 17:23
```
[2020-12-10 20:19:40] [INFO] [MiningManager] MiningManagerMainLoop TaskCanceledException: Отменена задача.
[2020-12-10 20:19:40] [INFO] [MiningManager] Exiting MiningManagerMainLoop run cleanup
[2020-12-10 20:19:40] [INFO] [MinerPluginsManager] Main Loop TaskCanceledException Отменена задача.
[2020-12-10 20:19:40] [INFO] [MiningManager] Exiting MiningManagerCommandQueueLoop run cleanup
[2020-12-10 20:19:40] [INFO] [UpdateHelpers] NhmAutoUpdateCheckLoop TaskCanceledException: Отменена задача.
[2020-12-10 20:19:40] [INFO] [UpdateHelpers] Exiting NhmAutoUpdateCheckLoop run cleanup
```

**Comment by netserver** [comment] 2020-12-10 17:34
same problem whith 4 rigs windows...

say  with wich app open nhm_windows_updater_3.0.5.5.check
  nhos ok

**Comment by EvgeniyKorepov** [comment] 2020-12-10 17:55
Resolve:
Manual download NiceHash Miner 3.0.5.5 zip package, unpack and copy overwrite exists NHM

**Comment by vgzhn** [comment] 2020-12-10 18:15
My rig is disabled until this is fixed. 
> Resolve:
> Manual download NiceHash Miner 3.0.5.5 zip package, unpack and copy overwrite exists NHM

This didn't help.
Might be better anyway to save some C02

EDIT: thanks rkresha, fixed so far

**Comment by rkresha** [comment] 2020-12-10 18:19
I downloaded it manually and turned off auto-update in the settings. So far so good.

**Comment by netserver** [comment] 2020-12-10 18:30
> Resolve:
> Manual download NiceHash Miner 3.0.5.5 zip package, unpack and copy overwrite exists NHM
of course manual update work. the issue is autoupdate.

**Comment by cccgeek** [comment] 2020-12-10 22:09
You can download the old 3.0.0.7 and let it auto upgrade to 3.0.5.5 as well... LOL! But seriously it works.

**Comment by netserver** [comment] 2020-12-11 02:48
i have one  rig remote without any remote  access, where i can deactive auto-update? i have sonoff to turn-off and turn-on but now autoudate close the mining.  its a headched  bad if turn autoupdate off bad if turn on...

**Comment by shubell** [comment] 2020-12-11 08:59
have this bug on all my rigs. Doesn't mater if it is win 7 or win 10  I can manually start nicehash miner but after a while i get the same popup if I don't disable updates.
![image](https://user-images.githubusercontent.com/12051070/101882922-d505ea80-3b96-11eb-89ef-5d3f25ff2e45.png)

**Comment by almartins** [comment] 2020-12-12 09:32
Same 3 rigs, 3 big problems.  Have solving doing that:
"
Manual download NiceHash Miner 3.0.5.5 zip package, unpack and copy overwrite exists NHM
of course manual update work. the issue is autoupdate.
"
Turn off automatically updating.
Very bad work from Nicehash with 3.05.5
Memory management seams working bad to - to many miner windows open and can't closed it !

**Comment by peteycrack420** [comment] 2020-12-14 22:27
> > Resolve:
> > Manual download NiceHash Miner 3.0.5.5 zip package, unpack and copy overwrite exists NHM
> > of course manual update work. the issue is autoupdate.

this is the only version is not working  auto or manually on one of my rigs

**Comment by S74nk0** [comment] 2021-01-04 12:10
This critical bug is present in 3.0.5.4 and 3.0.5.5 and some users are affected and might require a manual update. With 3.0.5.6 this bug is resolved.

**Closed as completed by S74nk0** 2021-01-04 12:10 UTC
Labels: bug
