### ISSUE TITLE
Gpu #0 no kernel image- MTP

### ISSUE THREAD

**Issue by dkrav97** [nicehash/NiceHashMiner#1465] opened 2019-03-20 03:45 UTC
The only miner that does not seem to recognize things is the CCminer for MTP, i keep getting the #0 kernel image not available. My gpu is gtx 970 and i have everything updated. no other miners seem to have any issues.... is this a known bug with the mtp miner?

any fixes?

**Comment by JoSoFine** [comment] 2019-03-24 17:18
i have the same problem with the same gpu. i have disabled mtp for now.
Benchmark does seem to work

**Comment by akaitani** [comment] 2019-04-06 15:02
[2019-04-06 18:01:39] Starting on stratum+tcp://mtp.hk.nicehash.com:3374
[2019-04-06 18:01:39] NVML GPU monitoring enabled.
[2019-04-06 18:01:39] NVAPI GPU monitoring enabled.
[2019-04-06 18:01:39] 1 miner thread started, using 'mtp' algorithm.

Same goes for me, I get this error message :

GPU #0: no kernel image is available for execution on the device

My GPU is GTX 940MX

**Comment by migtouron** [comment] 2019-04-09 06:32
Same problem with GTX 950M 

2019-04-09 08:28:41] Starting on stratum+tcp://mtp.eu.nicehash.com:3374
[2019-04-09 08:28:41] NVML GPU monitoring enabled.
[2019-04-09 08:28:41] NVAPI GPU monitoring enabled.
[2019-04-09 08:28:41] 1 miner thread started, using 'mtp' algorithm.
...
[2019-04-09 08:29:06] GPU #0: Intensity set to 16, 65536 cuda threads
Step 1 : Compute F(I) and store its T blocks X[1], X[2], ..., X[T] in the memory
Step 2 : Compute the root F of the Merkle hash tree
[2019-04-09 08:29:07] GPU #0: invalid device symbol
[2019-04-09 08:29:07] GPU #0: GeForce GTX 950M, 64.76 MH/s
[2019-04-09 08:29:07] GPU #0: no kernel image is available for execution on the device

**Comment by C-Lyon** [comment] 2019-05-24 01:48
[2019-05-23 19:47:45] Starting on stratum+tcp://mtp.usa.nicehash.com:3374
[2019-05-23 19:47:45] NVML GPU monitoring enabled.
[2019-05-23 19:47:45] NVAPI GPU monitoring enabled.
[2019-05-23 19:47:45] 1 miner thread started, using 'mtp' algorithm.
[2019-05-23 19:47:49] Stratum difficulty set to 1 (0.00000)
[2019-05-23 19:47:49] GPU #0: Intensity set to 16, 65536 cuda threads
Step 1 : Compute F(I) and store its T blocks X[1], X[2], ..., X[T] in the memory
Step 2 : Compute the root F of the Merkle hash tree
[2019-05-23 19:47:50] GPU #0: GeForce GTX 950M, 57.04 kH/s
[2019-05-23 19:47:50] GPU #0: no kernel image is available for execution on the device

**Comment by S74nk0** [comment] 2019-06-28 13:23
New version released [1.9.1.5](https://github.com/nicehash/NiceHashMinerLegacy/releases/tag/1.9.1.5) closing this issue. If the issue is present in the new release please open a new issue.

Closing.

**Closed as completed by S74nk0** 2019-06-28 13:23 UTC

**Comment by jakubsuchybio** [comment] 2019-06-29 18:42
Still doing it on 1.9.1.5 with NVIDIA 970 on ccminer.exe

**Comment by brandadaniel** [comment] 2019-07-14 14:55
same NVIDIA GTX970 here on 1.9.1.7 on ccminer.exe with same error:
[2019-07-14 09:54:36] GPU #0: no kernel image is available for execution on the device
