### ISSUE TITLE
"Check All Profitability" and "Check Single Profitability" buttons in Settings form returning 404 - Not Found

### ISSUE THREAD

**Issue by qwertydog** [nicehash/NiceHashMiner#1371] opened 2019-01-29 10:55 UTC
NHML Version: 1.9.0.10
Windows 10

**Check all profitability**
https://api.nicehash.com/p=calc&name=CUSTOM&speed30=767.57&speed31=772.59&speed32=1971734.00&speed34=772.19&speed5=727.90&speed8=1.13&speed14=39.62&speed20=32.19&speed21=2.58&speed23=0.28&speed24=456.35&speed26=11.90&speed27=1.69&speed28=3.67&speed29=29.18&speed33=10352087.00&speed36=50.33&nhmver=1.9.0.10&cost=1&power=1

**Check Single Profitability**
https://api.nicehash.com/p=calc&name=Intel(R)%20Core(TM)%20i5-3470%20CPU%20@%203.20GHz&speed30=160.10&speed31=59.10&speed32=168684.00&speed34=162.30&nhmver=1.9.0.10&cost=1&power=1

[log.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/2807334/log.txt)

![image](https://user-images.githubusercontent.com/12867537/51903489-2c769380-2421-11e9-8fc2-27a2f57e94f9.png)

**Comment by S74nk0** [comment] 2019-06-28 13:34
New version released [1.9.1.5](https://github.com/nicehash/NiceHashMinerLegacy/releases/tag/1.9.1.5) closing this issue. If the issue is present in the new release please open a new issue.

Closing.

**Closed as completed by S74nk0** 2019-06-28 13:34 UTC
