### ISSUE TITLE
my rig 3x gtx1050 ti having problem karnel 385.41 stop responding and recovered but not benchmarks or mining but 2 x 1050 ti work fine for 2days PLEASE HELP

### ISSUE THREAD

**Issue by romazic** [nicehash/NiceHashMiner#275] opened 2017-09-05 00:50 UTC
To keep development of NiceHash Miner Legacy streamlined please make sure the following are true before posting an issue:

- [ ] The issue has not already been reported.
- [ ] Relevant log files are included (generally `\logs\log.txt`).
- [ ] The issue is with NHML and not inherent of miner executables. This can be verified by launching the miner manually and looking for the error.
- [ ] The issue is relevant to NHML specifically and not to the NiceHash service.
- [ ] Specifications of setup such as NHML version, Windows version, and hardware are included.

**Comment by jimmyhackers** [comment] 2017-09-06 12:03
mine has the same issue. twice in two days ive come to my computer in the morning to find the gpu side of my mining program opening and instanly closing repeatedly. very worrying.

im going back to version 1.8.1.1

**Comment by jimmyhackers** [comment] 2017-09-06 12:16
i also get the nvidia driver error the same as yourself......the only thing i can assume is gpu boost is messing things up.

due to the low load/high specific load nature of mining some algo. im guessing gpu boost sees a load of headroom as the temps arn't to high....tries to boost the gpu clocks up but ends up going to far and crashing "

**Comment by DillonN** [comment] 2017-09-07 03:32
This happens if the display driver crashes, which can be caused by many things (OC, undervolt, corrupt system, SLI enabled, not enough power). Generally this is not a problem with NHML but with the drivers (the continuous reopening of miner windows is NHML detecting that the miners are crashing on launch and trying to relaunch them). Make sure you are using stock clocks and especially that SLI is disabled

**Comment by romazic** [comment] 2017-09-08 03:55
this happens only when u install 3rd Gpu otherwise no issue

**Comment by Sav87** [comment] 2017-09-09 13:03
If the error occurs when the miner algorithm is switched (also when benchmarking), pressing the stop button, this is the NHML error.

**Closed as completed** 2018-02-09 23:34 UTC
