### ISSUE TITLE
1.9.0.15 ccminer_mtp crashes 8 1070ti stock settings

### ISSUE THREAD

**Issue by salighie** [nicehash/NiceHashMiner#1409] opened 2019-02-21 13:59 UTC
Getting errors
GPU 4: out of memory 
GPU 4: Result for 000000000 does not validate  on CPU
NVIDIA Drivers 418.91

![image](https://user-images.githubusercontent.com/36240617/53174126-0757e980-35b7-11e9-958a-b85d68feaa58.png)

CUDA 10
![image](https://user-images.githubusercontent.com/36240617/53174471-e3e16e80-35b7-11e9-9624-8968e290dc42.png)

**Comment by serjeg3** [comment] 2019-02-21 17:44
тоже также 1070ti

**Comment by salighie** [comment] 2019-02-21 19:33
https://www.google.com/search?rlz=1C1ASUM_enUS782US782&ei=-vtuXOzHDcnN_AafhIPYAQ&q=what+does+%D1%82%D0%BE%D0%B6%D0%B5+%D1%82%D0%B0%D0%BA%D0%B6%D0%B5+mean&oq=what+does+%D1%82%D0%BE%D0%B6%D0%B5+%D1%82%D0%B0%D0%BA%D0%B6%D0%B5+mean&gs_l=psy-ab.3...2078.5362..5526...1.0..0.221.1730.9j6j1......0....1..gws-wiz.......0i8i7i30j33i299j33i160.bXpwfW4AMjU

**Comment by salighie** [comment] 2019-02-21 19:35
...not sure what i clicked - but didn't mean to close it.

**Comment by F1Rumors** [comment] 2019-02-24 13:58
Concur. Also seeing this, and GUI crashes too. Reliability is so poor I have had to disable that miner

**Comment by S74nk0** [comment] 2019-06-28 13:29
New version released [1.9.1.5](https://github.com/nicehash/NiceHashMinerLegacy/releases/tag/1.9.1.5) closing this issue. If the issue is present in the new release please open a new issue.

Closing.

**Closed as completed by S74nk0** 2019-06-28 13:29 UTC
