### ISSUE TITLE
AMD R9 390 not detected in NHML 1.8.2.0 Pre2

### ISSUE THREAD

**Issue by giosal** [nicehash/NiceHashMiner#746] opened 2017-12-21 13:50 UTC
Hi,

My AMD R9 390 is not detected in 1.8.2.0 Pre2, it used to work with driver version 17.11.1

But after updating to 17.12.1 it dissappeared and I think the problem is in the driver.

Please see the log (output of check_all_AMD.bat)
[debug_all_out_AMD.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/1579380/debug_all_out_AMD.txt)

**Update**

After rolling back driver to 17.11.1 it appeared again. So this should be resolved in next release

**Comment by endlessterror** [comment] 2017-12-21 17:40
Check the bugs first people! 

Possible duplicate of bug #1373

**Comment by giosal** [comment] 2017-12-21 23:26
I'm sorry, I couldn't find it.
In any case, this should be resolved in the future, as sometimes these drivers improve mining performance, especially for Vega cards.

**Comment by S74nk0** [comment] 2019-07-02 14:46
Issue related to old nhm version/build. Please use latest version and open a new issue for bugs and/or features.

**Closed as completed by S74nk0** 2019-07-02 14:46 UTC
