### ISSUE TITLE
Can't get profitability data

### ISSUE THREAD

**Issue by isazon4ik** [nicehash/NiceHashMiner#563] opened 2017-11-09 10:25 UTC
![2017-11-09 13 19 28](https://user-images.githubusercontent.com/8778152/32600577-1b53415a-c551-11e7-8e88-9908733b06e8.png)
![2017-11-09 13 20 01](https://user-images.githubusercontent.com/8778152/32600578-1b6f67fe-c551-11e7-8991-f13afad65c3b.png)

A few days on all rigs this problem started. Tried different versions - from 1.8.0.2 to 1.8.2.0 Pre, the problem is present everywhere. The checkbox "ignore the loss of the Internet connection" is removed, as seen in the screenshot.

**Comment by Munchies55** [comment] 2017-11-09 12:14
Im having the same issue, auto-start mining brings up the same "cant get profitability data" error and wont start mining, but if i close the error and click start it will start mining with no issue. version: 1.8.1.4

**Comment by ShortCircuit1** [comment] 2017-11-09 16:17
I am having the same problem. When 1.8.*.* not work, 1.7.*.* working without problem

**Comment by pet1777798** [comment] 2017-11-10 07:28
один день проработал и все
![default](https://user-images.githubusercontent.com/33540150/32647385-effed972-c601-11e7-9a82-34b16e6e11f2.jpg)

**Comment by isazon4ik** [comment] 2017-11-10 12:24
@DillonN man, it's important

**Comment by Picoskop** [comment] 2017-11-10 13:18
@isazon4ik I am having the same issue but first i get this error 
![screenshot_1](https://user-images.githubusercontent.com/33548106/32659961-2a4705cc-c621-11e7-918a-d27158a3067b.png)

after i press yes to continue and i press start i get this one 

![screenshot_2](https://user-images.githubusercontent.com/33548106/32659972-34ee5f20-c621-11e7-9bb7-bf4a5b4395f5.png)

The problem is my internet connection is working perfect (i have internet access) but from some reason i can't make connection to nicehash servers. And i can't even do benchmarks. Anyone has any idea why? Am i banned from nicehash servers? Or something else? But i never even connected to them in the first place :( 
Claymore for ethereum is working perfectly but i wanted to switch to nicehash to check it out and i am unable to connect but i can download miners from some reason (unknown aswell). Btw i tryed to turn off IPV6 and still the same issue.
Can someone please help with what should i try next?
P.S. i am using nicehash 1.8.1.5 and have tryed it on 1.8.1.4 and 1.8.2.0. Everywhere is the same error.

**Comment by DillonN** [comment] 2017-11-10 15:26
NHML requires a connection to NH servers to mine or benchmark. Many things can cause it to not connect, like server problems, firewall, ISP problems, etc. None of these can be fixed from NHML

@Munchies55 NHML constantly retries to connect, it's likely here it was able to connect before you clicked OK and so it mined properly. This is something I can look into improving - a more intuitive way to notify there is no connection that goes away if the problem is fixed, especially when automining

**Comment by isazon4ik** [comment] 2017-11-10 16:14
@DillonN Dude, the NHML is started from the BAT file, how to press the OK button? Do something already, tired of constantly going to the rigs and pressing this OK button. Because of this problem, I already lost 24h revenue. It's easier then to stop using the NHML and go to the pools.

**Comment by ShortCircuit1** [comment] 2017-11-10 22:18
why 1.7.6.3 work okey? 1.8 not okey. why ping, teamview, mining work ok? internet lost? NO!

**Comment by ShortCircuit1** [comment] 2017-11-10 22:23
I think NHML must starting "without internet", may be start with randomly or last algo, but NHML can not stopping with window!!!!

**Comment by Munchies55** [comment] 2017-11-11 02:04
@DillonN That would be great, i have only ever gotten the, "cant get profitablity data" error never the "no internet connection" one,

I have also tried disabling IPv6 which didnt help and also added outbound and inbound firewall rules for the NHML program, which also didnt fix the problem, neither did running as administrator, it always comes up whenever i have autostart mining on.

**Comment by aeratus** [comment] 2017-11-11 07:26
Hello colleagues!!!
At me too produces an error.
It is not possible to get NiceHash profitability data. If you are connected to the Internet, try again later. On versions 1.8.1.1; 1.8.1.3; 1.8.1.5. This is for those that I worked.

**Comment by DmitryDMR** [comment] 2017-11-11 21:36
@DillonN can you disable "cant get profitablity data" error window and run mining with last more profitable algos? i get this error very, very often

**Comment by Spritor** [comment] 2017-11-13 13:06
same issue with both 1.8.1.5 and 1.8.2.0 pre. anyone found any solution yet ?

**Comment by adri76** [comment] 2017-11-14 07:45
I have the same problem, I can only use 1.7.5.13, all the newer versions has the "no internet connection" problem. I have tried everything. 
1.7.5.13 works perfectly and I pinged all the servers no problem, but every version from 1.8..... does not work.

**Comment by chelnydiablo** [comment] 2017-11-14 15:29
+1  достала ошибка. в день по нескольку раз.

14.11.2017 18:17:17|Debug|WebSocket.sendHttpRequest|A response to this request:
                          HTTP/1.1 503 Service Temporarily Unavailable
                          Date: Tue, 14 Nov 2017 15:17:18 GMT
                          Content-Type: text/html
                          Transfer-Encoding: chunked
                          Connection: keep-alive
                          Set-Cookie: __cfduid=d47eb7675ab682a56f0917aadeeaf7208
1510672638; expires=Wed, 14-Nov-18 15:17:18 GMT; path=/; domain=.nicehash.com; H
ttpOnly
                          Server: cloudflare-nginx
                          CF-RAY: 3bdaefd948368fe7-DME
14.11.2017 18:17:17|Fatal|WebSocket.connect|Not a WebSocket handshake response.
14.11.2017 18:17:17|Debug|WebSocket.closeHandshake|Was clean?: False
                            sent: False
                            received: False
[18:17:18] [SOCKET] Connection closed: An error has occurred while connecting.
[18:17:19] [SOCKET] Socket connection unsuccessfull, will try again on next devi
ce update (1min)

 в логах:

[

> 2017-11-14 18:15:20] [INFO] [ComputeDeviceManager.Query] QueryCudaDevices END
> [2017-11-14 18:15:20] [INFO] [ComputeDeviceManager.Query] Skipping AMD device detection, settings set to disabled
> [2017-11-14 18:15:20] [INFO] [ComputeDeviceManager.Query] Cuda NVIDIA/CUDA device count GOOD
> [2017-11-14 18:15:20] [INFO] [ComputeDeviceManager.Query] AMD GPU device count GOOD
> [2017-11-14 18:15:21] [INFO] [ComputeDeviceManager.Query] virtual memory size GOOD
> [2017-11-14 18:15:21] [INFO] [SOCKET] Connection closed: An error has occurred while connecting.
> [2017-11-14 18:15:21] [INFO] [SOCKET] Attempting reconnect in 0 seconds
> [2017-11-14 18:15:21] [INFO] [SOCKET] Connection closed: An error has occurred while connecting.
> [2017-11-14 18:15:22] [INFO] [SOCKET] Connection closed: An error has occurred while connecting.
> [2017-11-14 18:15:24] [INFO] [SOCKET] Connection closed: An error has occurred while connecting.
> [2017-11-14 18:15:25] [INFO] [SOCKET] Connection closed: An error has occurred while connecting.
> [2017-11-14 18:15:26] [INFO] [SOCKET] Connection closed: An error has occurred while connecting.
> [2017-11-14 18:15:27] [INFO] [SOCKET] Connection closed: An error has occurred while connecting.
> [2017-11-14 18:15:29] [INFO] [SOCKET] Connection closed: An error has occurred while connecting.
> [2017-11-14 18:15:30] [INFO] [SOCKET] Connection closed: An error has occurred while connecting.
> [2017-11-14 18:15:31] [INFO] [SOCKET] Connection closed: An error has occurred while connecting.
> [2017-11-14 18:15:33] [INFO] [SOCKET] Connection closed: An error has occurred while connecting.
> [2017-11-14 18:15:34] [INFO] [SOCKET] Connection closed: An error has occurred while connecting.
> [2017-11-14 18:15:35] [INFO] [SOCKET] Connection closed: An error has occurred while connecting.
> [2017-11-14 18:15:36] [INFO] [SOCKET] Connection closed: An error has occurred while connecting.
> [2017-11-14 18:15:38] [INFO] [SOCKET] Connection closed: An error has occurred while connecting.
> [2017-11-14 18:15:39] [INFO] [SOCKET] Connection closed: An error has occurred while connecting.
> [2017-11-14 18:15:40] [INFO] [SOCKET] Connection closed: An error has occurred while connecting.
> [2017-11-14 18:15:41] [INFO] [SOCKET] Connection closed: An error has occurred while connecting.
> [2017-11-14 18:15:43] [INFO] [SOCKET] Connection closed: An error has occurred while connecting.
> [2017-11-14 18:15:44] [INFO] [SOCKET] Connection closed: An error has occurred while connecting.
> [2017-11-14 18:15:45] [INFO] [SOCKET] Connection closed: An error has occurred while connecting.
> [2017-11-14 18:15:46] [INFO] [NICEHASH] Bitcoin rate get
> [2017-11-14 18:15:47] [INFO] [NICEHASH] Current Bitcoin rate: 6642.20
> [2017-11-14 18:15:47] [INFO] [NICEHASH] Setting environment variables
> [2017-11-14 18:15:47] [INFO] [NICEHASH] Trying to enable/disable Windows error reporting
> [2017-11-14 18:15:47] [INFO] [NICEHASH] Current DontShowUI value: 1
> [2017-11-14 18:15:47] [INFO] [NICEHASH] nvidiasetp0state returned error code: 3
> [2017-11-14 18:16:46] [INFO] [SOCKET] Attempting reconnect in 26 seconds
> [2017-11-14 18:17:12] [INFO] [SOCKET] Connection closed: An error has occurred while connecting.
> [2017-11-14 18:17:14] [INFO] [SOCKET] Connection closed: An error has occurred while connecting.
> [2017-11-14 18:17:15] [INFO] [SOCKET] Connection closed: An error has occurred while connecting.
> [2017-11-14 18:17:16] [INFO] [SOCKET] Connection closed: An error has occurred while connecting.
> [2017-11-14 18:17:18] [INFO] [SOCKET] Connection closed: An error has occurred while connecting.
> [2017-11-14 18:17:19] [INFO] [SOCKET] Socket connection unsuccessfull, will try again on next device update (1min)
> [2017-11-14 18:18:18] [INFO] [SOCKET] Attempting reconnect in 26 seconds
> [2017-11-14 18:18:45] [INFO] [SOCKET] Connection closed: An error has occurred while connecting.
> [2017-11-14 18:18:46] [INFO] [SOCKET] Connection closed: An error has occurred while connecting.
> [2017-11-14 18:18:46] [INFO] [SOCKET] Socket connection unsuccessfull, will try again on next device update (1min)
> [2017-11-14 18:18:47] [INFO] [SOCKET] Connection closed: An error has occurred while connecting.
> [2017-11-14 18:18:48] [INFO] [SOCKET] Connection closed: An error has occurred while connecting.
> [2017-11-14 18:18:50] [INFO] [SOCKET] Connection closed: An error has occurred while connecting.
> [2017-11-14 18:18:51] [INFO] [SOCKET] Socket connection unsuccessfull, will try again on next device update (1min)
> [2017-11-14 18:19:50] [INFO] [SOCKET] Attempting reconnect in 22 seconds
> [2017-11-14 18:20:12] [INFO] [SOCKET] Connection closed: An error has occurred while connecting.
> [2017-11-14 18:20:14] [INFO] [SOCKET] Connection closed: An error has occurred while connecting.
> [2017-11-14 18:20:15] [INFO] [SOCKET] Connection closed: An error has occurred while connecting.
> [2017-11-14 18:20:16] [INFO] [SOCKET] Connection closed: An error has occurred while connecting.
> [2017-11-14 18:20:17] [INFO] [SOCKET] Connection closed: An error has occurred while connecting.
> [2017-11-14 18:20:19] [INFO] [SOCKET] Socket connection unsuccessfull, will try again on next device update (1min)
> [2017-11-14 18:20:46] [INFO] [SOCKET] Attempting reconnect in 20 seconds
> [2017-11-14 18:21:06] [INFO] [SOCKET] Connection closed: An error has occurred while connecting.
> [2017-11-14 18:21:08] [INFO] [SOCKET] Connection closed: An error has occurred while connecting.
> [2017-11-14 18:21:09] [INFO] [SOCKET] Connection closed: An error has occurred while connecting.
> [2017-11-14 18:21:10] [INFO] [SOCKET] Connection closed: An error has occurred while connecting.
> [2017-11-14 18:21:11] [INFO] [SOCKET] Connection closed: An error has occurred while connecting.
> [2017-11-14 18:21:13] [INFO] [SOCKET] Socket connection unsuccessfull, will try again on next device update (1min)
> [2017-11-14 18:21:46] [INFO] [SOCKET] Attempting reconnect in 21 seconds
> [2017-11-14 18:22:07] [INFO] [SOCKET] Connection closed: An error has occurred while connecting.
> [2017-11-14 18:22:09] [INFO] [SOCKET] Connection closed: An error has occurred while connecting.
> [2017-11-14 18:22:10] [INFO] [SOCKET] Connection closed: An error has occurred while connecting.
> [2017-11-14 18:22:11] [INFO] [SOCKET] Connection closed: An error has occurred while connecting.
> [2017-11-14 18:22:12] [INFO] [SOCKET] Connection closed: An error has occurred while connecting.
> [2017-11-14 18:22:14] [INFO] [SOCKET] Socket connection unsuccessfull, will try again on next device update (1min)
> [2017-11-14 18:22:46] [INFO] [SOCKET] Attempting reconnect in 16 seconds
> [2017-11-14 18:23:02] [INFO] [SOCKET] Connection closed: An error has occurred while connecting.
> [2017-11-14 18:23:04] [INFO] [SOCKET] Connection closed: An error has occurred while connecting.
> [2017-11-14 18:23:05] [INFO] [SOCKET] Connection closed: An error has occurred while connecting.
> [2017-11-14 18:23:06] [INFO] [SOCKET] Connection closed: An error has occurred while connecting.
> [2017-11-14 18:23:07] [INFO] [SOCKET] Connection closed: An error has occurred while connecting.
> [2017-11-14 18:23:09] [INFO] [SOCKET] Socket connection unsuccessfull, will try again on next device update (1min)
> [2017-11-14 18:23:46] [INFO] [SOCKET] Attempting reconnect in 29 seconds
> [2017-11-14 18:24:15] [INFO] [SOCKET] Connection closed: An error has occurred while connecting.
> [2017-11-14 18:24:17] [INFO] [SOCKET] Connection closed: An error has occurred while connecting.
> [2017-11-14 18:24:18] [INFO] [SOCKET] Connection closed: An error has occurred while connecting.
> [2017-11-14 18:24:19] [INFO] [SOCKET] Connection closed: An error has occurred while connecting.
> [2017-11-14 18:24:21] [INFO] [SOCKET] Connection closed: An error has occurred while connecting.
> [2017-11-14 18:24:22] [INFO] [SOCKET] Socket connection unsuccessfull, will try again on next device update (1min)
> [2017-11-14 18:24:46] [INFO] [SOCKET] Attempting reconnect in 20 seconds
> [2017-11-14 18:25:06] [INFO] [SOCKET] Connection closed: An error has occurred while connecting.
> [2017-11-14 18:25:08] [INFO] [SOCKET] Connection closed: An error has occurred while connecting.
> [2017-11-14 18:25:09] [INFO] [SOCKET] Connection closed: An error has occurred while connecting.
> [2017-11-14 18:25:10] [INFO] [SOCKET] Connection closed: An error has occurred while connecting.
> [2017-11-14 18:25:12] [INFO] [SOCKET] Connection closed: An error has occurred while connecting.
> [2017-11-14 18:25:13] [INFO] [SOCKET] Socket connection unsuccessfull, will try again on next device update (1min)
> [2017-11-14 18:25:46] [INFO] [SOCKET] Attempting reconnect in 11 seconds
>

**Comment by dstarcev** [comment] 2017-11-14 20:54
Cloudflare is randomly banning websocket requests to https://api.nicehash.com/v2/nhm

Cloudflare произвольно блокирует соединение вебсокетов https://api.nicehash.com/v2/nhm

**Comment by danialmoghaddam** [comment] 2017-11-15 00:46
Come on guys! It is so obvious that there is a problem. Have it fixed in the next version please. This is costing us some loss!

**Comment by Sav87** [comment] 2017-11-17 07:43
It is necessary to change the algorithm of autorun, issuing messages and receiving data from the Internet.

**Comment by ShortCircuit1** [comment] 2017-11-18 14:03
I'm tired of this error and switched to Linux. now everything works like a clock
я устал от этой ошибки и перешел на линукс. теперь все работает как часы

**Comment by Sav87** [comment] 2017-11-18 15:36
add Pull request #625

**Comment by xtrime-ru** [comment] 2017-12-01 18:31
@Sav87 сделал исправления для этой ошибки, их одобрили, но пока не включили в релиз. 
Пока ждем релиз я скомпилировал его исправления:
https://github.com/xtrime-ru/NiceHashMinerLegacy-SMA-FIX/releases

**Comment by jesteroi** [comment] 2018-02-12 09:47
I got the same problem with 1.8.1.8 not getting profitability data.

I checked my time sync and I was out by 1600ms. So I updated my time sync a couple times so it was down to within +/- 5ms and then ran NHLM again and it worked.

Can't say that this is what solved the problem for sure, but my NHLM is working again.

I used this: http://www.timesynctool.com/

**Closed as completed** 2018-02-19 04:24 UTC
