### ISSUE TITLE
Screen stays on when mining *.19

### ISSUE THREAD

**Issue by techman05** [nicehash/NiceHashMiner#1470] opened 2019-03-24 00:43 UTC
When I have nicehash miner *.19 mining my monitor doesn't shut off automatically after a set time. hope this is fixable.

**Comment by techman05** [comment] 2019-04-02 01:33
Seems to not be happening in *.20

**Comment by S74nk0** [comment] 2019-06-28 13:23
New version released [1.9.1.5](https://github.com/nicehash/NiceHashMinerLegacy/releases/tag/1.9.1.5) closing this issue. If the issue is present in the new release please open a new issue.

Closing.

**Closed as completed by S74nk0** 2019-06-28 13:23 UTC
