### ISSUE TITLE
Miner v1.9.2.11 constantly crashing after a few minutes of use

### ISSUE THREAD

**Issue by Ravko3** [nicehash/NiceHashMiner#1714] opened 2019-08-09 03:24 UTC
Regardless of whether I am benchmarking or running the miner, it will crash randomly after a few minutes. This happens with all recent versions of Nice Hash. Any help?

**Comment by Ravko3** [comment] 2019-08-09 03:25
[log.txt](https://github.com/nicehash/NiceHashMiner/files/3484607/log.txt)
 Here is the log.

**Comment by luc1an24** [comment] 2019-08-09 07:00
Hi @Ravko3
Thank you for reporting this bug.
There seems to be a problem with the compatibility of miners and your operating system.
Could you please run CreateLogReport.exe and send me the archived logs?
You can send them to domen.kirnkrefl@nicehash.com so no personal data will be public.

Thank you for your help.

**Comment by luc1an24** [comment] 2019-08-19 06:27
@Ravko3 confirmed that this is not a bug.
Closing.

**Closed as completed by luc1an24** 2019-08-19 06:27 UTC
