### ISSUE TITLE
1.9.0.13 not working

### ISSUE THREAD

**Issue by viper357** [nicehash/NiceHashMiner#1387] opened 2019-02-14 14:53 UTC
Version .13 simply does not launch when clicking the exe. Had to delete it and go back to using .12 version.

**Comment by viper357** [comment] 2019-02-14 14:56
[2019-02-14 14:42:33] [INFO] [NICEHASH] Starting up NiceHashMiner v1.9.0.13
[2019-02-14 14:42:33] [INFO] [NICEHASH] Selected language: English
[2019-02-14 14:42:33] [INFO] [NICEHASH] Critical error: missing language
[2019-02-14 14:42:33] [INFO] [NICEHASH] WMI service seems to be running, ManagementObjectSearcher returned success.
[2019-02-14 14:42:50] [INFO] [NICEHASH] Starting up NiceHashMiner v1.9.0.13
[2019-02-14 14:42:50] [INFO] [NICEHASH] Selected language: English
[2019-02-14 14:42:50] [INFO] [NICEHASH] Critical error: missing language
[2019-02-14 14:42:50] [INFO] [NICEHASH] WMI service seems to be running, ManagementObjectSearcher returned success.
[2019-02-14 14:43:28] [INFO] [NICEHASH] Starting up NiceHashMiner v1.9.0.13
[2019-02-14 14:43:28] [INFO] [NICEHASH] Selected language: English
[2019-02-14 14:43:28] [INFO] [NICEHASH] Critical error: missing language
[2019-02-14 14:43:28] [INFO] [NICEHASH] WMI service seems to be running, ManagementObjectSearcher returned success.
[2019-02-14 14:45:23] [INFO] [NICEHASH] Starting up NiceHashMiner v1.9.0.13
[2019-02-14 14:45:23] [INFO] [NICEHASH] Selected language: English
[2019-02-14 14:45:23] [INFO] [NICEHASH] Critical error: missing language
[2019-02-14 14:45:23] [INFO] [NICEHASH] WMI service seems to be running, ManagementObjectSearcher returned success.
[2019-02-14 14:48:54] [INFO] [NICEHASH] Starting up NiceHashMiner v1.9.0.13
[2019-02-14 14:48:54] [INFO] [NICEHASH] Selected language: English
[2019-02-14 14:48:54] [INFO] [NICEHASH] Critical error: missing language
[2019-02-14 14:48:54] [INFO] [NICEHASH] WMI service seems to be running, ManagementObjectSearcher returned success.

**Comment by EtaYorius** [comment] 2019-02-14 16:14
Same issue as above, it simply doing nothing at all when trying to open it... nothing, not even a message or error.

**Comment by Oriny** [comment] 2019-02-14 17:11
Same issue i have testing and seems delete content of configs except for benchmark fix  problem.....and aplication starting again....according to facebook deleting general is enought.

**Comment by tdkryger** [comment] 2019-02-14 19:03
Same issue. Deleting general.json works, but as it has to done every time the app needs to be started, it's not a fix.

**Comment by EtaYorius** [comment] 2019-02-15 03:48
I tried what someone suggested, it worked. but i restarted the PC and now i need to do all that again and run benchmarks too... this versions is completely broken.

**Comment by Oriny** [comment] 2019-02-15 10:11
It seem dowload new version an reinstall fix the problem, becouse the problem is fix already ....someone try it ?

**Comment by Oriny** [comment] 2019-02-15 10:20
Confirmed...problem is already fixed in newest version avaible for download.

**Comment by yury21** [comment] 2019-02-15 13:36
Newest version 1.9.0.13   is not working properly.

**Comment by Sealr0x** [comment] 2019-02-15 17:55
[2019-02-14 14:42:33] [INFO] [NICEHASH] Selected language: English
[2019-02-14 14:42:33] [INFO] [NICEHASH] Critical error: missing language

**Comment by S74nk0** [comment] 2019-06-28 13:32
New version released [1.9.1.5](https://github.com/nicehash/NiceHashMinerLegacy/releases/tag/1.9.1.5) closing this issue. If the issue is present in the new release please open a new issue.

Closing.

**Closed as completed by S74nk0** 2019-06-28 13:32 UTC
