### ISSUE TITLE
v1.9.0.12 gminer - remains open

### ISSUE THREAD

**Issue by KadarMarine** [nicehash/NiceHashMiner#1379] opened 2019-02-07 03:13 UTC

**Comment by KadarMarine** [comment] 2019-02-07 03:32
Often, when NiceHashMinerLegacy v1.9.0.12 is "Stopped" or goes into "CURRENTLY MINING NOT PROFITABLE" mode; while it is mining with gminer, the gminer window does not shut down. It remains running as though no shut down command was ever received.

I believe this is leading to numerous rig crashes when NiceHashMinerLegacy later tries to use those same GPUs being used by the unstopped gminer to start mining again with those same GPUs (and/or algos).

Using NVIDEA GPUs power set to 90%, and under-clocked by -50.
Windows 7 Pro (64bit) SP1
Intel Pentium CPU G3260 @ 3.30 Ghz
8 Gigs of installed RAM; 32 Gigs of Virtual Memory set.

**Comment by BoooLT** [comment] 2019-02-13 14:18
Same there, 5 different rigs, all win7 64bit, no OC cards, gminer remains operating even nicehash is closed. Bminer works correctly.

Update: win 8.1 gminer works correctly. So its win 7  issue?

**Comment by KadarMarine** [comment] 2019-03-03 19:52
> Same there, 5 different rigs, all win7 64bit, no OC cards, gminer remains operating even nicehash is closed. Bminer works correctly.
> 
> Update: win 8.1 gminer works correctly. So its win 7 issue?

I've just released NhlRigMinder v1.5 (04/22/19):
https://kadarmarine-ftp.sharefile.com/d-sdbf8bd0130c4decb

Update includes numerous fixes and improvements. Server is stress tested to 63 "Zombie Rig" clients.

New Wake on LAN (WoL) options provide more complete automation.

Requires Windows XP or better running on an IBM based PC.

Cheers:)

**Comment by S74nk0** [comment] 2019-06-28 13:33
New version released [1.9.1.5](https://github.com/nicehash/NiceHashMinerLegacy/releases/tag/1.9.1.5) closing this issue. If the issue is present in the new release please open a new issue.

Closing.

**Closed as completed by S74nk0** 2019-06-28 13:33 UTC
