### ISSUE TITLE
*.20 saying need benchmark then completes real fast?

### ISSUE THREAD

**Issue by techman05** [nicehash/NiceHashMiner#1481] opened 2019-03-31 22:06 UTC
I tried to turn team red miner on and ran benchmarks and set it to start on complete. It appears to complete and then it says more need to be benchmarked. I say yes and then it immediately flashes to "benchmark complete". I acknowledge and  the miner starts.

I'm using amd radeon rx 580 and rx560 and 6th gen intel.

**Comment by S74nk0** [comment] 2019-04-01 08:31
@techman05 Send zipped logs folder.

**Comment by techman05** [comment] 2019-04-02 00:00
Hopefully this is what you need.
[logs.zip](https://github.com/nicehash/NiceHashMinerLegacy/files/3031782/logs.zip)

**Comment by luc1an24** [comment] 2019-04-02 06:07
@techman05 The new version of xmr-stak doesn't work well on AMD cards, so I suggest that you disable all xmr-stak gpu algorithms.
Even if there are some algorithms that aren't benchmarked you can stil mine, just click "No" when you are asked to benchmark them or even better disable those that can't be benchmarked

**Comment by S74nk0** [comment] 2019-06-28 13:21
New version released [1.9.1.5](https://github.com/nicehash/NiceHashMinerLegacy/releases/tag/1.9.1.5) closing this issue. If the issue is present in the new release please open a new issue.

Closing.

**Closed as completed by S74nk0** 2019-06-28 13:21 UTC
