### ISSUE TITLE
Windows unexpected reboot when mining with 2 1080ti

### ISSUE THREAD

**Issue by wawamr2** [nicehash/NiceHashMiner#1541] opened 2019-05-24 12:25 UTC
Asus ROG maximus formula IX
I7-7700k @ 5GHZ
2x 1080ti not overclock
Corsair AX1200i
custom liquid cooling GPU max@42C, CPU max@62C

I can mine on nicehash miner legacy v1.9.0.22 with CPU and GPU1, but as soon as I add GPU2 Windows will unexpectedly reboot while mining.

Not happening if I use the old Nicehash miner 2

Always the GPU2 that cause the crashing. You think something is wrong with GPU2? Why not happening with Nicehash miner 2?

Thanks
wawamr2

**Comment by S74nk0** [comment] 2019-06-04 11:23
@wawamr2 You will need to provide `logs`. **Nicehash miner 2** is using **excavator** that is more stable (both products are on hold and aren't actively developed) this is the reason you aren't having crashes on nhm2.

**Comment by S74nk0** [comment] 2019-06-28 13:20
New version released [1.9.1.5](https://github.com/nicehash/NiceHashMinerLegacy/releases/tag/1.9.1.5) closing this issue. If the issue is present in the new release please open a new issue.

Closing.

**Closed as completed by S74nk0** 2019-06-28 13:20 UTC
