### ISSUE TITLE
Can not see 11, 12 video card?

### ISSUE THREAD

**Issue by vasy01** [nicehash/NiceHashMiner#1411] opened 2019-02-22 03:09 UTC
Can not see 11, 12 video card? window does not expand)
==
Make the window nicehash, it was possible to fix anywhere on the screen, so that after restarting Windows, it remained where it was fixed.
===
Не видно 11, 12 видеокарту? окно не расширить)
==
Сделайте чтоб окно nicehash, можно было фиксировать в любом месте экрана, чтоб после перезагрузке Виндовс, оно оставалось где зафиксировал.
==
![2019-02-22](https://user-images.githubusercontent.com/47653806/53217219-0dae9a00-3679-11e9-929e-4c94a0e956e3.png)

**Comment by S74nk0** [comment] 2019-06-28 13:28
New version released [1.9.1.5](https://github.com/nicehash/NiceHashMinerLegacy/releases/tag/1.9.1.5) closing this issue. If the issue is present in the new release please open a new issue.

Closing.

**Closed as completed by S74nk0** 2019-06-28 13:28 UTC
