### ISSUE TITLE
CryptoNight issues on CPU and GPU

### ISSUE THREAD

**Issue by ryderbg** [nicehash/NiceHashMiner#515] opened 2017-11-02 19:05 UTC
Hello! I just heard about CryptoNight price up and decided to switch to it. I have several machines and my main desktop PC is mining when idle. GPU is **Sapphire R9 Nitro Fury** and CPU is **Intel i7 4790k**. I am using v1.8.1.4 but can't pass the benchmark of CryptoNight Claymore and Sgminer. Also CPU miners are staying at 0 h/s. I tried older version and CPU miners still staying 0 h/s so I assume it is a network issue. But for GPU in older version of Nicehash I can pass benchmark but the speed is too slow. For Fury it must be 800 mh/s and for me is 250 mh/s. Another machine that I have (4 x Sapphire rx480) are running on 2500 mh/s. So I think there is a issue with my Fury. Anyone can help?

**Comment by snowcrawl** [comment] 2017-11-02 19:27
I am also noticing problems with this algorithm especially with the Nvidia cards.   I have tried switching service location.   Sometimes it helps, but a lot of trouble connecting.

**Comment by ryderbg** [comment] 2017-11-02 19:52
But it cannot pass the benchmark.

**Comment by snowcrawl** [comment] 2017-11-02 21:12
Yes, I could not get my R9 380 AMD card to pass the Claymore CryptoNight benchmark either.  I suspect it could have something to do with the amount of traffic on that mining pool today.  I gave up on trying to get this R9 card to pass the sgminer CryptoNight, since it often has crashed my system during the Benchmark.   So I think if you were somehow able to get it to pass just Claymore, that would be adequate.  Or else use an older version of the NiceHash Legacy mining software, if you still had one, in which that card had passed the benchmark on CryptoNight.
 I tried "Precise", which usually works.   However it would just time out after trying it a few different times.   So I decided to dig up an older version of Nicehash miner in which that R9 380 card had passed the benchmark and now am running two different instances of NiceHash Miner in order to get that older card running CryptoNight, with my other cards running on the current version of NiceHash Legacy.   However I am noticing that the Stats page is reporting 0 KH/s very frequently on certain workers.   I am not sure if it is simply a problem with the reporting on the Stats page, or if the miners are still able to send the work.   I have read before that if the miner software says that the shares are accepted then it is working.

**Comment by Balzhur** [comment] 2017-11-03 07:24
There is also an issue with "read speed zero" and miner restart. Difficulty for Cryptonight had been increased significantly recently - from 80k to 200k. Now NHML just restarts CPU and GPU miner every two minutes effectively disrupting mining, when several days ago xmrig worked for days without issues. I had to shut NHML down and launch xmrig and xmrig-nvidia manually.

**Comment by fajyfcbq** [comment] 2017-11-03 07:42
![2017-11-03_073404](https://user-images.githubusercontent.com/33342649/32364020-8b07f5d6-c083-11e7-91d1-09bfbaf22ea1.jpg)
![2017-11-03_073546](https://user-images.githubusercontent.com/33342649/32364046-a5a4d2e2-c083-11e7-9387-c38b445416dd.jpg)

**Comment by fajyfcbq** [comment] 2017-11-03 07:43
Здравствуйте. Может кто то знает с чем это связано.

**Comment by drkskwlkr** [comment] 2017-11-03 08:10
@fajyfcbq Right now NiceHash (the service, not this software!) is undergoing stratum server maintenance.

From [Nicehash Twitter feed](https://twitter.com/NiceHashMining):
> Dear users, we'll be performing scheduled maintenance on stratum servers, API & website on Nov 3rd @ 09:00 UTC. Thank you for your patience.

**Comment by andicole0** [comment] 2017-11-03 10:41
I have had issues with Cryptonight for the last 24 hrs, so it's not the current maintenance. My CPU is running Cryponight but my R9 and RX are doing nothing. I get pop ups with -
[20:27:14] Started sgminer 5.5.5-gm-nicehash-8
[20:27:14] * using Jansson 2.7
Can I select something other than Cryptonight?
Andi.

**Comment by snowcrawl** [comment] 2017-11-03 21:01
Yes Andi,

If you click on the Settings button, then click on the Device/Algorithms Tab.   You will then be able to deselect the CryptoNight algorithm for your device by removing the check mark next to that algorithm.
Then click "Save and close".   Then restart your mining software.

**Comment by andicole0** [comment] 2017-11-04 09:10
Thanks. It seems to have resolved itself, running quite happily now.

**Comment by rchar081** [comment] 2017-11-04 15:05
Yea Still getting the 0 Speed issue on cryptonight algorithm for stats on the nicehash statistics. Damn.

**Comment by Rickochey** [comment] 2017-11-04 19:25
same, constant disconnects on cryptonite with AMD and Nvidia

**Comment by kfadrat** [comment] 2017-11-04 19:52
i have the same problem. On prev version of NHML, the cpu part was showing and dissapearing, on 1.8.2.0 its always 0H/s slthough the miner window shows something. On GPU there is no problem like that. Screenshot https://imgur.com/a/uq19X

**Comment by francescocmazza** [comment] 2017-11-04 20:26
I have the same problem. Strange that my GPU seems to connect correctly most of the time, instead CPU engine always fails to connect.

**Comment by streaml1ne555** [comment] 2017-11-04 20:40
Not showing hashrate for CPU is a bug since 1.8.1.4 and Dillon knows about it. Some of my XMRig's are having issues connecting to the NiceHash's cryptonight stratum servers but I think that's probably because they're getting crushed since everything is mining that lately..

**Comment by MaKla89** [comment] 2017-11-07 22:11
sounds to be the same issue as in this thread:
https://github.com/nicehash/NiceHashMiner/issues/1319

@streaml1ne555 : you mentioned the shown hashrate being a bug. does this meant that it's only a visual and the mining IS working in the background?

**Comment by streaml1ne555** [comment] 2017-11-07 22:14
Correct, if you open the xmr-stak-cpu window and hit the h key it should show you an actual hash rate so it is mining. It appears to only be a display issue with the NiceHash interface.

**Comment by MaKla89** [comment] 2017-11-07 22:25
ah thanks, if thats true, i would not really mind, but I don't know how the accounting (and payout-stuff) is being calculated by nicehash if the data is not even shown correctly in the web-interface :S

**Comment by CreamyG31337** [comment] 2017-11-08 05:49
the CPU part is fixed with latest release but ccminer cryptonight is still not being read properly by nicehash. I can't reproduce the problem consistently. Sometimes it shows hashrate and submitted shares fine in the ccminer stats, but 0 H/s in nicehash, and also warnings in the log about the speed being zero, cooldown or whatever, then it restarts. Right now it's working fine with whatever combination of cards I try, so I can't give much more detail.

**Comment by CreamyG31337** [comment] 2017-11-08 06:12
[log-bug.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/1452748/log-bug.txt)

**Comment by MaKla89** [comment] 2017-11-08 07:44
oh okay, I let Nicehash cpu-mine over night and even though it still says "0 H/s" in nicehash, i was granted some "Total BTC" for CryptoNight. So I guess that eventhough CPU-mining is very slow and nicehash posted (via twitter) that very slow devices are currently problematic / temporarily not supported, it seems to be working in the most important way: Granting you BTC for processing power. okay.. very little controlability, but it is working :)

**Comment by streaml1ne555** [comment] 2017-11-08 16:41
> ah thanks, if thats true, i would not really mind, but I don't know how the accounting (and payout-stuff) is being calculated by nicehash if the data is not even shown correctly in the web-interface :S

When your system completes work it sends it to the NiceHash servers, the accounting stuff is handled there. If you upgrade to 1.8.1.5 the bug is fixed for xmr-stak-cpu.

**Comment by streaml1ne555** [comment] 2017-11-08 16:45
> the CPU part is fixed with latest release but ccminer cryptonight is still not being read properly by nicehash. I can't reproduce the problem consistently. Sometimes it shows hashrate and submitted shares fine in the ccminer stats, but 0 H/s in nicehash, and also warnings in the log about the speed being zero, cooldown or whatever, then it restarts. Right now it's working fine with whatever combination of cards I try, so I can't give much more detail.

It seems that the hashrate not showing up correctly is some problem with the nicehash website and how far back it looks for received work. It's like a yo-yo, sometimes the hashrate shown on nicehash.com is high, sometimes it's low depending on when you refresh it and when your system submits completed work.

**Comment by exallon72** [comment] 2017-11-11 19:32
The sgminer-gm seems to not work at all. it will fail immediately on start.
When using cryptonight Johnson 2.7 or something like that.

[dump.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/1464027/dump.txt)

**Closed as completed** 2018-02-14 02:27 UTC
