### ISSUE TITLE
v 1.9.1.5 messed up power settings

### ISSUE THREAD

**Issue by VadimEv** [nicehash/NiceHashMiner#1583] opened 2019-06-29 15:36 UTC
I just downloaded 1.9.1.5 stopped 1.9.0.23 and suddenly seen surge in vent rpms.
When I checked both Afterburner and Thundermuster (yep, they do both coexist flawlessly) - since sometimes AB alone messes up some of mem clock / vent settings,
And I found that 4 of my retail cards on that rig was suddenly at 100% power.  Turns out NHML 1.9.1.5  BY DEFAULT touches my power settings.

I barely resisted urge to wipe this pic of shareware from my rig, but decided to give it a try.

Don't make low power version, every sane "experienced" miner already uses some OC/power management tools. 
For example, it will be much much better and expected if there was a checkbox "Let HNML manage OC/power settings".

**Comment by X-miner** [comment] 2019-06-29 16:57
I have the same issue, i have 2 RTX 2080 Ti that run at 1/5 of the usual speed with this new version, how the hell i can fix it? 
![Annotazione 2019-06-29 185250](https://user-images.githubusercontent.com/52356302/60387186-bb0a4200-9a9f-11e9-9f80-7ee3b5540f25.png)

**Comment by X-miner** [comment] 2019-06-29 18:13
All my GPUs dropped like crazy in hashrate and power , why????  And even if i use older version of NHML same performances... what is going on??? How can i fix this???
![Annotazione 2019-06-29 201218](https://user-images.githubusercontent.com/52356302/60387894-50aacf00-9aaa-11e9-8a85-26b080d59b39.png)

**Comment by AtlAntA118** [comment] 2019-06-29 21:51
Having the same problems with a 6x1070ti rig and a 6x1070rig. Also on a 1080.. Only a reboot fixed it.

**Comment by X-miner** [comment] 2019-06-29 22:45
> Having the same problems with a 6x1070ti rig and a 6x1070rig. Also on a 1080.. Only a reboot fixed it.

You just rebooted your rig/pc and they worked again at top performance?

**Comment by boldheart007** [comment] 2019-06-30 03:19
Still same whatever tried restarting
Locked msi afterburner profiles
After every restart should load msi afterburner profile manually

**Comment by AtlAntA118** [comment] 2019-06-30 07:18
> > Having the same problems with a 6x1070ti rig and a 6x1070rig. Also on a 1080.. Only a reboot fixed it.
> 
> You just rebooted your rig/pc and they worked again at top performance?

Yes. But not with 1.9.1.5. With the old .23

Perhaps because i set afterburner to apply overclocks at startup. Manually resetting them didnt work though.

**Comment by Jfro416** [comment] 2019-06-30 08:42
Had the same issue with both RX 570 & 580 cards. I removed one to rule out hardware issues after uninstalling everything + drivers and the issue still happened. NHML would freeze up and Radeon settings/Afterburner would also stop.
A restart helped for 2-3 minutes and it started again.

I looked into the last windows updates as when I upgraded NH to 1.9.1.5 the issue started but rolling back did not help. After a process on windows updates deleting and testing/reinstalling, the removal of update KB4502584 seems to have resolved the issue.

Going to let it run for a while still but if your having this issue, take a look at deleting that update. Hash rate seems to be back to normal as well.

**Comment by S74nk0** [comment] 2019-06-30 08:44
Setting NVIDIA GPUs to Low power mode was a mistake. We have re-released 1.9.1.5 where the default settings are set to High. I recommend for anybody that has this issue to download again the new [zip package](https://github.com/nicehash/NiceHashMinerLegacy/releases/download/1.9.1.5/nhm_windows_1.9.1.5.zip).

**Comment by ne0rrmatrix** [comment] 2019-06-30 19:29
Fixed for nvidia on S74nk0 updated version above. No issues for me. Checking AMD then will edit post to reflect. Ok nvidia power automatically goes to 100 percent on start but manually setting afterburner afterwards fixes it.

AMD works but i have to disable claymore miner and use pheonix as it won't work with 4GB cards on algo's it selects. But hashrate is good with pheonix.

**Comment by X-miner** [comment] 2019-06-30 21:08
Fixed for my 1080Ti but my 2 2080ti are still performing very badly and for some reason they are on Cuckatoo29 and not 31 , and the power is still less than half of previous version
![Annotazione 2019-06-30 230727](https://user-images.githubusercontent.com/52356302/60402152-0437c000-9b8c-11e9-896c-7a2c8197ee7d.png)

**Comment by X-miner** [comment] 2019-07-01 01:47
Same story with nbminer Grin31, the power setup for my 2 2080ti is too low (less then half of the previous version) consequentially the hashrate is very low too. How can i fix this?
![Annotazione 2019-07-01 034520](https://user-images.githubusercontent.com/52356302/60405843-f47fa200-9bb2-11e9-8349-4e8ce9ee67ae.png)

**Comment by X-miner** [comment] 2019-07-01 05:26
I tried also with MSI Afterburner and i managed to improve a bit the situation but the 2nd 2080ti is working at ridiculous hashpower and the power is very low aswell also the GPU clock is super low , like 1/4 of the 1st 2080ti, i dunno what`s going on here. Both the GPUs are the same model and have identical MSI Afterburner settings and same Nvidia control panel settings. 
![Annotazione 2019-07-01 072057](https://user-images.githubusercontent.com/52356302/60412463-80082b80-9bd1-11e9-95d4-c53f3bc1258d.png)

**Comment by frazier345** [comment] 2019-07-01 18:56
I had to either remove my config files for the cards and rebenchmark or goto the Configs folder, Open up the config file for each GPU and Check "Power Target:" Set to 100000 for 100%  on my Nvidia 1070s I also noticed that "Power Level" was 0 on the old config and set to 2 on the new config.  

This is what i did. It might work for you but not guaranteeing it.

**Comment by X-miner** [comment] 2019-07-01 23:35
Thank you frazier, can you specifically tell me the path of the config file that you modified? Is  the NBMIner config one? Thank you so much in advance.

**Comment by frazier345** [comment] 2019-07-02 00:22
It was the config file for each GPU  So Configs/Bennchmark_GPU-xxxxxxxx.json

**Comment by X-miner** [comment] 2019-07-02 02:20
Thank u frazier gonna modify it and let u know. Really appreciated.

**Comment by X-miner** [comment] 2019-07-02 06:21
I modified the config but still nothing. My 1080ti is at 300 watt and going at full throttle with NBMiner but only 1 2080ti, of my 2, 
![Annotazione 2019-07-02 081347](https://user-images.githubusercontent.com/52356302/60488478-608d0380-9ca2-11e9-82c7-e5a19d0a9ed5.png)
is going at more than 200 watt always with NBMiner while the 2nd twin identical 2080ti is at 80 watt and the GPU clock is 300-500 instead of 1200+ of the 1st 2080ti. Both the 2080ti have the same parameters on the json config files and the same settings on afterburner, this is a mistery to me, if someone can help i will be really grateful...

**Comment by prettycode** [comment] 2019-07-02 07:25
I'm also having weird power issues on my 1080 tis (all identical, CUDA 10). I've always used a bat file and nvidiaInspector.exe to manually set my power configuration (runs at startup, with a delay of `timeout /t 180` before executing nvidiaInspector.exe commands).

After installing 1.9.1.5, none of the power-related settings from nvidiaInspector.exe (e.g. `-lockVoltagePoint` and `-setPowerTarget`) are being respected when they always were previously (use HWINFO64 to monitor). Oddly, on some rigs, a couple GPUs are running at 165 - 170W all the time, while the rest are running at 260 - 270W. 😭

GPU config files show:

```
"PowerTarget": 100000,
"PowerLevel": 2
```

Only useful potentially related thing I can find in the log files:

```
[2019-07-01 20:14:34] [INFO] [SystemSpecs] virtual memory size GOOD
[2019-07-01 20:14:34] [INFO] [NvidiaMonitorManager] tryAddNvmlToEnvPath
[2019-07-01 20:14:34] [INFO] [NvidiaMonitorManager] NVML HANDLE:140703167955864
[2019-07-01 20:14:34] [INFO] [NvidiaMonitorManager] NVML HANDLE:140703168046680
[2019-07-01 20:14:34] [ERROR] [NVML] System.Exception: NVML nvmlDeviceGetPowerManagementLimitConstraints failed with status: NoPermission
   at NHM.DeviceMonitoring.DeviceMonitorNVIDIA.SetTdp(Double tdpPerc, UInt32 defaultLimit) in D:\Programming\NiceHashMinerLegacy\src\NHM.DeviceMonitoring\DeviceMonitorNVIDIA.cs:line 201
   at NHM.DeviceMonitoring.DeviceMonitorNVIDIA.SetTdpSimple(PowerLevel level) in D:\Programming\NiceHashMinerLegacy\src\NHM.DeviceMonitoring\DeviceMonitorNVIDIA.cs:line 221
[2019-07-01 20:14:35] [INFO] [MinerPluginsManager] Finished initialization of miners.
[2019-07-01 20:14:35] [ERROR] [CPUDIAG] System.InvalidOperationException: Cannot load Counter Name data because an invalid index '' was read from the registry.
   at System.Diagnostics.PerformanceCounterLib.GetStringTable(Boolean isHelp)
   at System.Diagnostics.PerformanceCounterLib.get_NameTable()
   at System.Diagnostics.PerformanceCounterLib.get_CategoryTable()
   at System.Diagnostics.PerformanceCounterLib.CounterExists(String category, String counter, Boolean& categoryExists)
   at System.Diagnostics.PerformanceCounterLib.CounterExists(String machine, String category, String counter)
   at System.Diagnostics.PerformanceCounter.InitializeImpl()
   at System.Diagnostics.PerformanceCounter.Initialize()
   at System.Diagnostics.PerformanceCounter.NextSample()
   at System.Diagnostics.PerformanceCounter.NextValue()
   at NHM.DeviceMonitoring.DeviceMonitorCPU.get_Load() in D:\Programming\NiceHashMinerLegacy\src\NHM.DeviceMonitoring\DeviceMonitorCPU.cs:line 31
```

Nothing about my setup has changed, and have no programs like MSI Afterburner running.

**Comment by prettycode** [comment] 2019-07-02 07:36
> Setting NVIDIA GPUs to Low power mode was a mistake. We have re-released 1.9.1.5 where the default settings are set to High. I recommend for anybody that has this issue to download again the new [zip package](https://github.com/nicehash/NiceHashMinerLegacy/releases/download/1.9.1.5/nhm_windows_1.9.1.5.zip).

Can you elaborate on this? Is this something I can manually modify in configs without having to update all my rigs by installing the re-release?

**Comment by ne0rrmatrix** [comment] 2019-07-02 10:04
for anyone that downloaded v1.9.1.5 it was updated the other day without a version change and you might want to check out the updated version to see if it fixes any issues you have.

**Comment by X-miner** [comment] 2019-07-02 17:06
> for anyone that downloaded v1.9.1.5 it was updated the other day without a version change and you might want to check out the updated version to see if it fixes any issues you have.

All my low power issue are still in place (at least for 1 of my 2080ti card, as i have described in the posts above) using the updated version of 1.9.1.5, so the issue is still in place.

**Comment by AtlAntA118** [comment] 2019-07-03 08:26
> > for anyone that downloaded v1.9.1.5 it was updated the other day without a version change and you might want to check out the updated version to see if it fixes any issues you have.
> 
> All my low power issue are still in place (at least for 1 of my 2080ti card, as i have described in the posts above) using the updated version of 1.9.1.5, so the issue is still in place.

Looks like this will be customizable in a future update. https://github.com/nicehash/NiceHashMinerLegacy/issues/1602

Until then im not using 1.5. If suddenly all my cards are using max power im pretty sure something will burn out. be it risers or PSU or a breaker. im not risking it. I want control of my cards. And i want to do it with an external program like afterburner or inspector.

**Comment by X-miner** [comment] 2019-07-03 16:05
I hope so. What i dont understand is why 1 of my 2 2080ti is going at 300 Mhz clock and the other one is going at 1400+ , they are both identical and same Afterburner settings. It appear that NHML override any setting and decide by itself also ignoring the config file. I was wondering if it was a question of overheating, since the 2 cards are mounted together in the same mobo (ROG STRIX X399-E GAMING) but is not the case cause when i enable only that card is still running at 300 Mhz and low power alone... very frustrating.

**Comment by vasyapupkin1** [comment] 2019-07-03 16:36
I set powerlimits via Afterburner for NVidia cards. Nicehash resets it at start. Not good.

**Comment by xtrime-ru** [comment] 2019-07-03 19:13
Same problem. Cant migrate from 1.9.0.x because of this.

**Comment by S74nk0** [comment] 2019-07-04 09:16
We will close this issue on next release. 
https://github.com/nicehash/NiceHashMinerLegacy/issues/1602#issuecomment-508407884

**Comment by S74nk0** [comment] 2019-07-04 10:16
New version released [1.9.1.6](https://github.com/nicehash/NiceHashMinerLegacy/releases/tag/1.9.1.6)

**Closed as completed by S74nk0** 2019-07-04 10:16 UTC
Labels: bug, Close on next release

**Comment by dalalyan** [comment] 2019-07-04 18:35
Problem still exists. When I run the executable(version 1.9.1.6), MSI Afterburner power limit values are raising to 100% for all installed graphic cards.

**Comment by VadimEv** [comment] 2019-07-04 19:28
Please check the setting. There is now checkbox which FORBIDS interference with power settings, you'll need to scroll down a bit and check it, by default NHM still messes up with power, UI still kinda suxx TT.

**Comment by dalalyan** [comment] 2019-07-04 19:38
> Please check the setting. There is now checkbox which FORBIDS interference with power settings, you'll need to scroll down a bit and check it, by default NHM still messes up with power, UI still kinda suxx TT.

Thanks for the info, that helped!!!
Just need to check the "Disable Device Power Mode Settings" checkbox from "Settings"->"Advanced" tab.
