### ISSUE TITLE
v 1.8.1.1 surges 1080 

### ISSUE THREAD

**Issue by sorg111** [nicehash/NiceHashMiner#180] opened 2017-08-19 04:41 UTC
NiceHashMinerLegacy v 1.8.1.1
While mining via the miner skunk, voltage sags on the chart
graphics card 1080. It is possible as that to correct? Screenshot attached.
![1080 skunk](https://user-images.githubusercontent.com/29475386/29483561-913662ac-84b1-11e7-8a9a-8116ddc51c04.jpg)

**Comment by drkskwlkr** [comment] 2017-08-19 08:17
@sorg111 What you are showing is _not_ a voltage drop but _change of the GPU power output over time_. If you check the GPU load chart, you will be able to notice the reason for this, especially if you modify the polling rate of MSI Afterburner monitor from 1000 ms to 500 ms or even 250ms.

You will clearly observe that rather than keeping the GPU at 99-100% steady for long periods of time like other algos, Skunk has a slightly different behavior where every couple of seconds it will drop GPU load from 100% to 90% or even less. The card responds by moving away from the power limit (i.e. drawing less power).

So even though I can't explain why Skunk doesn't keep the card permanently loaded at maximum, the power limit chart is a perfectly normal behavior when the GPU load changes in such pattern.

P.S. What I find surprising for myself is that I my Skunk hashrate is much lower than yours at similar settings (I get around 37 MH/s on a Gigabyte GTX1080 G1 Gaming to your 41 MH/s). But, I have no explanation for that either :)

P.P.S. For purpose of issue-tracking, this is **not** related to NHML 1.8.1.1 but to Skunk, and is **not a problem/bug** but normal behavior (ticket should be closed).

**Comment by 3zero2** [comment] 2017-08-19 13:19
Skunk definitely operates in the way being described above. 

Strange thing is that 1080ti achieved 55 mh/s and a titan Xp only gets 50 mh/s.

**Comment by sorg111** [comment] 2017-08-19 16:17
Спасибо, а я боялся за карту)

**Comment by juanfpina** [comment] 2017-08-19 18:10
Is ~42Mh/s normal for your 1080? I only get at most 38 with a higher OC.

**Comment by sorg111** [comment] 2017-08-19 18:33
I don't know is normal or not. I just ran this algorithm on the miner. Trying to understand that now is better to get to 1080.

**Comment by streaml1ne555** [comment] 2017-08-19 21:14
Make sure your card is running in P0, that could make up some MH/s. Get the latest nvidiaprofileinspector and in section 5 there's an option to use P2 for Cuda, disable it and reboot. Might help.

**Comment by DillonN** [comment] 2017-08-22 14:29
Like @drkskwlkr said this is expected behaviour with Skunk mining. In the future miners might be more optimized. Closing this now

**Closed as completed by DillonN** 2017-08-22 14:29 UTC
