### ISSUE TITLE
Cant start Gminer - every time getting memory anti-hacking message / GTX1080Ti

### ISSUE THREAD

**Issue by Magelanas** [nicehash/NiceHashMiner#1399] opened 2019-02-18 12:34 UTC
**NOTE this issue tracker is for NiceHashMinerLegacy bugs/feature requests ONLY! If you need general help or have a support question related to NHM2 please look at https://www.nicehash.com/support first and open a ticket there if your issue is not specifically NHML related**

For general help there are several community resources available, such as https://reddit.com/r/NiceHash

To keep development of NiceHash Miner Legacy streamlined please make sure the following are true before posting an issue:

- Please make requests in English
- The issue has not already been reported.
- **Relevant log files are included (generally `\logs\log.txt`).**
- **The issue is with NHML and not inherent of miner executables.** This can be verified by launching the miner manually and looking for the error.
- **The issue is relevant to NHML specifically and not to the NiceHash service OR NHM2.** (see above)
- Specifications of setup such as NHML version, Windows version, and hardware are included.

Note this is a guide, you can delete this text once you ensure enough information is given

**Comment by Magelanas** [comment] 2019-02-18 12:35
![screenshot_1](https://user-images.githubusercontent.com/47745070/52951407-6a186d80-338a-11e9-8c8b-e490c94eeed7.jpg)

**Comment by smgagarin** [comment] 2019-05-13 20:20
Start having the same issue today. Didn't change anything. Miner just started show this error message,
Anybody know how to fix this issue?

**Comment by toffick** [comment] 2019-05-15 08:55
also got this issue

**Comment by S74nk0** [comment] 2019-06-28 13:30
New version released [1.9.1.5](https://github.com/nicehash/NiceHashMinerLegacy/releases/tag/1.9.1.5) closing this issue. If the issue is present in the new release please open a new issue.

Closing.

**Closed as completed by S74nk0** 2019-06-28 13:30 UTC
