### ISSUE TITLE
NHML-1.8.1.3 not the correct cost of algorithms!

### ISSUE THREAD

**Issue by boyod** [nicehash/NiceHashMiner#361] opened 2017-09-26 06:57 UTC
windows 10 (64). 
for AMD RX470
 Mining on one algorithm CryptoNight gives out approximately 0.6 $, but its cost in BTC / Day is lower than others which give out about 0.4 $ !!! Thus, the choice of the optimal algorithm is not working !!!

[log.1.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/1332075/log.1.txt)
[log.txt](https://github.com/nicehash/NiceHashMinerLegacy/files/1332076/log.txt)

**Comment by DillonN** [comment] 2017-09-26 09:06
Not sure what you're saying exactly, that CryptoNight is more profitable for you but it's not being chosen? Make sure you have accurate values for benchmark speed, switching won't work if NHML doesn't know the correct speeds

**Comment by boyod** [comment] 2017-09-26 17:09
Yes CryptoNight is more profitable but it's not being chosen! I restarted the benchmark but nothing changed. Speed for CryptoNight almost corresponds to mine. The speed at the test for other protocols does not correspond to the real one, i.e. At testing it is higher than at mining approximately in 2 times!

**Comment by boyod** [comment] 2017-09-26 17:44
I have several different graphics cards (AMD and NVIDIA) and I chose a 16GB swap file in the system as recommended. After I put the swap file at the choice of the system, the speed of the benchmark began to coincide with the speed at the mining!

**Comment by DillonN** [comment] 2017-09-29 00:09
@boyod yes having insufficient swap could cause benchmarks to be higher, since they are only running one miner at a time but during mining several are run at once. Are you saying the issue is fixed now? If you are unable to get a large enough swap you can lower the hashrates for the other algorithms manually in the settings page

**Closed as completed** 2018-02-11 03:15 UTC
