### ISSUE TITLE
BitDefender going crazy on NiceHash.

### ISSUE THREAD

**Issue by DoubleThePsycho** [nicehash/NiceHashMiner#2043] opened 2020-04-23 03:13 UTC
Hi there, I've been using the past couple of hours trying to install NiceHash, but for some reason, BitDefender keeps blocking it, even after following your instructions, as well as going multiple pages in on Google. The only thing I haven't tried is uninstalling it, and that I don't wanna do... Are there any fixes for this?

**Comment by luc1an24** [comment] 2020-04-24 06:26
Hi @DoubleThePsycho 
Thank you for reaching out!
Could you try to temporary (during the install phase) disable it?
Probably it still deletes any new files downloaded during installation phase.
After that you can enable it back and you will see if files in exclusion folder do not get deleted.

Have a nice day!

**Comment by ronin2230** [comment] 2020-04-28 03:55
I just re-installed and windows immediately flagged and deleted; I know how to add exceptions but can we see the root cause to this or maybe a solution I missed? thanks in advance!

**Comment by khayto** [comment] 2020-05-05 18:04
disable windows defender, download nicehash and extract it. open windows defender settings, add exception, select folder, click nicehash folder. reenable windows defender, start nicehash. thats all there is to it.

**Comment by ronin2230** [comment] 2020-05-05 19:25
thanks much

**Comment by luc1an24** [comment] 2020-06-22 08:10
Looks like the issue was fixed, therefore closing the ticket.
Have a nice mining!

**Closed as completed by luc1an24** 2020-06-22 08:10 UTC
