### ISSUE TITLE
Issue with TTMiner - Protocol EthProxy-Stratum

### ISSUE THREAD

**Issue by traxinv** [nicehash/NiceHashMiner#1530] opened 2019-05-16 07:14 UTC
Good day,

I am having issues with TT-Miner. When it connects to the stratum server 172.65.195.77:3374 Protocol EthProxy-Stratum.

Get an error: Unknown Protocol - cannot continue
Here is an image of the mining window:
![image](https://user-images.githubusercontent.com/3995322/57833766-1962b600-77bb-11e9-9529-7d022d688c09.png)

OS: Windows 10
NHLM: 1.9.0.21 - Download the latest miners as well
GPU: 9 x GTX1060 6GB

**Comment by jwesolo** [comment] 2019-05-17 06:41
This has been happening on both my systems (Windows 10, 1 x GTX 1080 each) for about a week or two now. It always seems to last for multiples of 30 minutes. Today it was 90 and 120 minutes. Usually if I hit 'q' in TT-Miner it restarts and works fine. I can lose hours of mining before noticing, though. It would be nice if TT-Miner would restart on its own if this error occurs more than a few times.

It was widespread for awhile but Nicehash said they fixed it. I read something about possible DDoS attacks on some of their servers; don't know if it was legit. Changing regions helps if the restart doesn't. Others are having this problem too:

https://www.reddit.com/r/NiceHash/comments/bp92xz/connection_error_on_mtp_server_anyone/
https://www.reddit.com/r/NiceHash/comments/bnaw1j/lost_connection_to_mtp/

I don't think it's a miner issue, but the miner could do some things to mitigate the problems. Nicehash needs to address this and tell us what is going on because I can't find anything from them except that statement 5 days ago saying all is well.

**Comment by nnasonov** [comment] 2019-05-30 07:47
I have the same issue now, with newer version. NHLM: 1.9.0.22

**Comment by jwesolo** [comment] 2019-05-30 16:27
As I suggested above, this issue is unrelated to NHML. I also no longer feel that it is a problem with the Nicehash pool service. It seems to be a problem with TT-Miner (see https://bitcointalk.org/index.php?topic=5025783.msg51236289#msg51236289 for a recent report that apparently will be getting a fix soon with TT-Miner version 2.2.6).

**Comment by S74nk0** [comment] 2019-06-04 11:07
The issue is not related to NHML. You can try [1.9.0.23](https://github.com/nicehash/NiceHashMinerLegacy/releases/tag/1.9.0.23) or **recommended** [1.9.1.4](https://github.com/nicehash/NiceHashMinerLegacy/releases/tag/1.9.1.4). Both have new TT-Miner version 2.2.5.

Closing issue not related to NHML.

**Closed as completed by S74nk0** 2019-06-04 11:07 UTC
